<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Cyclistic Bike-Share Case Study | Nnamdi Okoli</title><meta name=keywords content><meta name=description content="Table of ContentsScenarioIn this case, I am assuming the role of a junior data analyst working in the marketing and analytics team at Cyclistic, a bike-share company in Chicago with two types of customers. The director of marketing believes the company’s future success depends on maximizing the number of annual memberships. Customers who buy single-ride or full-day passes are known as casual riders, while the customers who purchase annual memberships are known as members."><meta name=author content="Nnamdi Okoli"><link rel=canonical href=/portfolio/cyclistic-bike/><meta name=google-site-verification content="XYZabc"><meta name=yandex-verification content="XYZabc"><meta name=msvalidate.01 content="XYZabc"><link crossorigin=anonymous href=/assets/css/stylesheet.bf5f9f73cf17311d52cedbcda82c922e91b2f566d88a85ad9f5b5a08b586bd5f.css integrity="sha256-v1+fc88XMR1SztvNqCySLpGy9WbYioWtn1taCLWGvV8=" rel="preload stylesheet" as=style><script defer crossorigin=anonymous src=/assets/js/highlight.acb54fd32bbc1982428b8850317e45d076b95012730a5936667e6bc21777692a.js integrity="sha256-rLVP0yu8GYJCi4hQMX5F0Ha5UBJzClk2Zn5rwhd3aSo=" onload=hljs.initHighlightingOnLoad()></script>
<link rel=icon href=favicon.ico><link rel=icon type=image/png sizes=16x16 href=favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=favicon-32x32.png><link rel=apple-touch-icon href=apple-touch-icon.png><link rel=mask-icon href=safari-pinned-tab.svg><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--hljs-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><meta property="og:title" content="Cyclistic Bike-Share Case Study"><meta property="og:description" content="Table of ContentsScenarioIn this case, I am assuming the role of a junior data analyst working in the marketing and analytics team at Cyclistic, a bike-share company in Chicago with two types of customers. The director of marketing believes the company’s future success depends on maximizing the number of annual memberships. Customers who buy single-ride or full-day passes are known as casual riders, while the customers who purchase annual memberships are known as members."><meta property="og:type" content="article"><meta property="og:url" content="/portfolio/cyclistic-bike/"><meta property="article:section" content="portfolio"><meta property="article:published_time" content="2023-07-15T00:00:00+00:00"><meta property="article:modified_time" content="2023-07-15T00:00:00+00:00"><meta property="og:site_name" content="NnamdiOkoli"><meta name=twitter:card content="summary"><meta name=twitter:title content="Cyclistic Bike-Share Case Study"><meta name=twitter:description content="Table of ContentsScenarioIn this case, I am assuming the role of a junior data analyst working in the marketing and analytics team at Cyclistic, a bike-share company in Chicago with two types of customers. The director of marketing believes the company’s future success depends on maximizing the number of annual memberships. Customers who buy single-ride or full-day passes are known as casual riders, while the customers who purchase annual memberships are known as members."><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":2,"name":"Portfolios","item":"/portfolio/"},{"@type":"ListItem","position":3,"name":"Cyclistic Bike-Share Case Study","item":"/portfolio/cyclistic-bike/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Cyclistic Bike-Share Case Study","name":"Cyclistic Bike-Share Case Study","description":"Table of Contents\rScenario\rIn this case, I am assuming the role of a junior data analyst working in the marketing and analytics team at Cyclistic, a bike-share company in Chicago with two types of customers. The director of marketing believes the company’s future success depends on maximizing the number of annual memberships. Customers who buy single-ride or full-day passes are known as casual riders, while the customers who purchase annual memberships are known as members.","keywords":[],"articleBody":"\rTable of Contents\rScenario\rIn this case, I am assuming the role of a junior data analyst working in the marketing and analytics team at Cyclistic, a bike-share company in Chicago with two types of customers. The director of marketing believes the company’s future success depends on maximizing the number of annual memberships. Customers who buy single-ride or full-day passes are known as casual riders, while the customers who purchase annual memberships are known as members. Therefore, the team wants to understand how casual riders and annual members use Cyclistic bikes differently. From these insights, the team will design a new marketing strategy to convert casual riders into annual members. But first, Cyclistic executives must approve the recommendations, so they must be backed up with compelling data insights and professional data visualizations.\rCharacters and teams.\nAsking questions and problem definition\rAsk the right questions\rIn this step, I asked myself questions such as ‘How do annual members and casual riders use Cyclistic bikes differently?’ to guide my analysis. Lily Moreno believes that the annual Members were more profitable than the casual riders. The goal before me is to assist the marketing team analyze the contrast between casual riders and members with the aim of providing recommendations that will aid the conversion of casual riders into annual members to maximize profits.\nHow do annual members and casual riders use Cyclistic bikes differently?\rWhy would casual riders buy Cyclistic annual memberships?\rHow can Cyclistic use digital media to influence casual riders to become members?\rIdentify the business task\rA bike-share program that features more than 5,800 bicycles and 600 docking stations. Cyclistic sets itself apart by also offering reclining bikes, hand tricycles, and cargo bikes, making bike-share more inclusive to people with disabilities and riders who can’t use a standard two-wheeled bike. The majority of riders opt for traditional bikes; about 8% of riders use the assistive options. Cyclistic users are more likely to ride for leisure, but about 30% use them to commute to work each day.\nIdentifying key stakeholders\rLily Moreno: The director of marketing and your manager. Moreno is responsible for the development of campaigns and initiatives to promote the bike-share program. These may include email, social media, and other channels.\nCyclistic marketing analytics team: A team of data analysts who are responsible for collecting, analyzing, and reporting data that helps guide Cyclistic marketing strategy. You joined this team six months ago and have been busy learning about Cyclistic’s mission and business goals — as well as how you, as a junior data analyst, can help Cyclistic achieve them.\nCyclistic executive team: The notoriously detail-oriented executive team will decide whether to approve the recommended marketing program\nApproach\rData analysis is a crucial step in solving problems. It is the process of collecting, organizing, and interpreting data to answer questions and reach conclusions. By analyzing data, businesses, organizations, and individuals can identify patterns and trends that can help them make informed decisions and improve their performance. This will involve sorting the data into categories and performing calculations or visualizing it with charts and graphs. I will also examine the data for any outliers or inconsistencies that may indicate a problem. After the data has been analyzed, it is important to interpret the results. This involves examining the data to identify any patterns or trends that may be present. It is also important to consider any potential causes of the problem, such as internal processes or external factors.\nPrepare the data\rThe data used for this analysis is located at (https://divvy-tripdata.s3.amazonaws.com/index.html), The data is made available under this (https://ride.divvybikes.com/data-license-agreement) I downloaded the most recent 12 months from February 2022 to January 2023 and stored them locally. This version of my analysis was done using R, spreadsheet, and Tableau. The dataset has no user ID or any specific commuter identifier, so the data on duplicate riders are not present.\nSort and filter the data in a spreasheet\rI checked for incomplete values in all columns\rI checked for duplicate values\rI checked for outliers\rUtilize R and RStudio\rGiven the size of the dataset after inspection with Excel, I decided on using R for analysis and specifically R studio.\nLoaded the packages\rlibrary(tidyverse)\rlibrary(ggplot2)\rlibrary(lubridate)\rlibrary(skimr)\rUpload the data files and create data frames\rfeb_2022 \u003c- read_csv(\"2022_02-divvy-tripdata.csv\")\r## Rows: 115609 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rmar_2022 \u003c- read_csv(\"2022_03-divvy-tripdata.csv\")\r## Rows: 284042 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rapr_2022 \u003c- read_csv(\"2022_04-divvy-tripdata.csv\")\r## Rows: 371249 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rmay_2022 \u003c- read_csv(\"2022_05-divvy-tripdata.csv\")\r## Rows: 634858 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rjun_2022 \u003c- read_csv(\"2022_06-divvy-tripdata.csv\")\r## Rows: 769204 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rjul_2022 \u003c- read_csv(\"2022_07-divvy-tripdata.csv\")\r## Rows: 823488 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\raug_2022 \u003c- read_csv(\"2022_08-divvy-tripdata.csv\")\r## Rows: 785932 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rsep_2022 \u003c- read_csv(\"2022_09-divvy-tripdata.csv\")\r## Rows: 701339 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\roct_2022 \u003c- read_csv(\"2022_10-divvy-tripdata.csv\")\r## Rows: 558685 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rnov_2022 \u003c- read_csv(\"2022_11-divvy-tripdata.csv\")\r## Rows: 337735 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rdec_2022 \u003c- read_csv(\"2022_12-divvy-tripdata.csv\")\r## Rows: 181806 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rjan_2023 \u003c- read_csv(\"2023_01-divvy-tripdata.csv\")\r## Rows: 190301 Columns: 13\r## ── Column specification ────────────────────────────────────────────────────────\r## Delimiter: \",\"\r## chr (7): ride_id, rideable_type, start_station_name, start_station_id, end_...\r## dbl (4): start_lat, start_lng, end_lat, end_lng\r## dttm (2): started_at, ended_at\r## ## ℹ Use `spec()` to retrieve the full column specification for this data.\r## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\rCheck for column consistency\rView to make sure all have the same columns and combine the 12 dataframes into one dataframe and give it a name.\ncolnames(feb_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(mar_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(apr_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(may_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(jun_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(jul_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(aug_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(sep_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(oct_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(nov_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(dec_2022)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rcolnames(jan_2023)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rstr(jan_2023)\r## spc_tbl_ [190,301 × 13] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\r## $ ride_id : chr [1:190301] \"F96D5A74A3E41399\" \"13CB7EB698CEDB88\" \"BD88A2E670661CE5\" \"C90792D034FED968\" ...\r## $ rideable_type : chr [1:190301] \"electric_bike\" \"classic_bike\" \"electric_bike\" \"classic_bike\" ...\r## $ started_at : POSIXct[1:190301], format: \"2023-01-21 20:05:42\" \"2023-01-10 15:37:36\" ...\r## $ ended_at : POSIXct[1:190301], format: \"2023-01-21 20:16:33\" \"2023-01-10 15:46:05\" ...\r## $ start_station_name: chr [1:190301] \"Lincoln Ave \u0026 Fullerton Ave\" \"Kimbark Ave \u0026 53rd St\" \"Western Ave \u0026 Lunt Ave\" \"Kimbark Ave \u0026 53rd St\" ...\r## $ start_station_id : chr [1:190301] \"TA1309000058\" \"TA1309000037\" \"RP-005\" \"TA1309000037\" ...\r## $ end_station_name : chr [1:190301] \"Hampden Ct \u0026 Diversey Ave\" \"Greenwood Ave \u0026 47th St\" \"Valli Produce - Evanston Plaza\" \"Greenwood Ave \u0026 47th St\" ...\r## $ end_station_id : chr [1:190301] \"202480.0\" \"TA1308000002\" \"599\" \"TA1308000002\" ...\r## $ start_lat : num [1:190301] 41.9 41.8 42 41.8 41.8 ...\r## $ start_lng : num [1:190301] -87.6 -87.6 -87.7 -87.6 -87.6 ...\r## $ end_lat : num [1:190301] 41.9 41.8 42 41.8 41.8 ...\r## $ end_lng : num [1:190301] -87.6 -87.6 -87.7 -87.6 -87.6 ...\r## $ member_casual : chr [1:190301] \"member\" \"member\" \"casual\" \"member\" ...\r## - attr(*, \"spec\")=\r## .. cols(\r## .. ride_id = col_character(),\r## .. rideable_type = col_character(),\r## .. started_at = col_datetime(format = \"\"),\r## .. ended_at = col_datetime(format = \"\"),\r## .. start_station_name = col_character(),\r## .. start_station_id = col_character(),\r## .. end_station_name = col_character(),\r## .. end_station_id = col_character(),\r## .. start_lat = col_double(),\r## .. start_lng = col_double(),\r## .. end_lat = col_double(),\r## .. end_lng = col_double(),\r## .. member_casual = col_character()\r## .. )\r## - attr(*, \"problems\")=\rCombine the data frames into one data frame\rfeb_2022 \u003c- mutate(feb_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rmar_2022 \u003c- mutate(mar_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rapr_2022 \u003c- mutate(apr_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rmay_2022 \u003c- mutate(may_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rjun_2022 \u003c- mutate(jun_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rjul_2022 \u003c- mutate(jul_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\raug_2022 \u003c- mutate(aug_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rsep_2022 \u003c- mutate(sep_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\roct_2022 \u003c- mutate(oct_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rnov_2022 \u003c- mutate(nov_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rdec_2022 \u003c- mutate(dec_2022, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rjan_2023 \u003c- mutate(jan_2023, ride_id = as.character(ride_id)\r,rideable_type = as.character(rideable_type))\rall_trips \u003c- bind_rows(feb_2022, mar_2022, apr_2022, may_2022, jun_2022, jul_2022,\raug_2022, sep_2022, oct_2022, nov_2022, dec_2022, jan_2023)\rInspect the new data frame\rPerform an inspection to confirm that the data has remained accurate after the combination, use data observed in the spreadsheet as a reference point for confirmation.\ncolnames(all_trips)\r## [1] \"ride_id\" \"rideable_type\" \"started_at\" ## [4] \"ended_at\" \"start_station_name\" \"start_station_id\" ## [7] \"end_station_name\" \"end_station_id\" \"start_lat\" ## [10] \"start_lng\" \"end_lat\" \"end_lng\" ## [13] \"member_casual\"\rstr(all_trips)\r## tibble [5,754,248 × 13] (S3: tbl_df/tbl/data.frame)\r## $ ride_id : chr [1:5754248] \"E1E065E7ED285C02\" \"1602DCDC5B30FFE3\" \"BE7DD2AF4B55C4AF\" \"A1789BDF844412BE\" ...\r## $ rideable_type : chr [1:5754248] \"classic_bike\" \"classic_bike\" \"classic_bike\" \"classic_bike\" ...\r## $ started_at : POSIXct[1:5754248], format: \"2022-02-19 18:08:41\" \"2022-02-20 17:41:30\" ...\r## $ ended_at : POSIXct[1:5754248], format: \"2022-02-19 18:23:56\" \"2022-02-20 17:45:56\" ...\r## $ start_station_name: chr [1:5754248] \"State St \u0026 Randolph St\" \"Halsted St \u0026 Wrightwood Ave\" \"State St \u0026 Randolph St\" \"Southport Ave \u0026 Waveland Ave\" ...\r## $ start_station_id : chr [1:5754248] \"TA1305000029\" \"TA1309000061\" \"TA1305000029\" \"13235\" ...\r## $ end_station_name : chr [1:5754248] \"Clark St \u0026 Lincoln Ave\" \"Southport Ave \u0026 Wrightwood Ave\" \"Canal St \u0026 Adams St\" \"Broadway \u0026 Sheridan Rd\" ...\r## $ end_station_id : chr [1:5754248] \"13179\" \"TA1307000113\" \"13011\" \"13323\" ...\r## $ start_lat : num [1:5754248] 41.9 41.9 41.9 41.9 41.9 ...\r## $ start_lng : num [1:5754248] -87.6 -87.6 -87.6 -87.7 -87.6 ...\r## $ end_lat : num [1:5754248] 41.9 41.9 41.9 42 41.9 ...\r## $ end_lng : num [1:5754248] -87.6 -87.7 -87.6 -87.6 -87.6 ...\r## $ member_casual : chr [1:5754248] \"member\" \"member\" \"member\" \"member\" ...\rsummary(all_trips)\r## ride_id rideable_type started_at ## Length:5754248 Length:5754248 Min. :2022-02-01 00:03:18.00 ## Class :character Class :character 1st Qu.:2022-06-02 15:18:09.50 ## Mode :character Mode :character Median :2022-07-27 22:50:40.50 ## Mean :2022-07-29 13:28:03.16 ## 3rd Qu.:2022-09-22 20:34:47.25 ## Max. :2023-01-31 23:56:09.00 ## ## ended_at start_station_name start_station_id ## Min. :2022-02-01 00:09:37.00 Length:5754248 Length:5754248 ## 1st Qu.:2022-06-02 15:37:50.50 Class :character Class :character ## Median :2022-07-27 23:09:33.00 Mode :character Mode :character ## Mean :2022-07-29 13:47:21.50 ## 3rd Qu.:2022-09-22 20:53:25.25 ## Max. :2023-02-04 04:27:03.00 ## ## end_station_name end_station_id start_lat start_lng ## Length:5754248 Length:5754248 Min. :41.64 Min. :-87.84 ## Class :character Class :character 1st Qu.:41.88 1st Qu.:-87.66 ## Mode :character Mode :character Median :41.90 Median :-87.64 ## Mean :41.90 Mean :-87.65 ## 3rd Qu.:41.93 3rd Qu.:-87.63 ## Max. :42.07 Max. :-87.52 ## ## end_lat end_lng member_casual ## Min. : 0.00 Min. :-88.14 Length:5754248 ## 1st Qu.:41.88 1st Qu.:-87.66 Class :character ## Median :41.90 Median :-87.64 Mode :character ## Mean :41.90 Mean :-87.65 ## 3rd Qu.:41.93 3rd Qu.:-87.63 ## Max. :42.37 Max. : 0.00 ## NA's :5899 NA's :5899\rData summary, addressing missing data and the linitations of the data\rSome of the data columns have missing values this will be dealt with in the cleaning process.\rA lot of user data is not available due to privacy issues.\rProcessing the data by cleaning\rThis phase involves checking for any data errors, cleaning the data of any errors, transforming said data by adding, then renaming and by removing data as needed, the rounding it up by checking to see that the data is clean and ready for analysis.\nAdd colums\rAdding columns for: date, month, day, ride_length, year, day_of_week, and hour\nall_trips$date \u003c- as.Date(all_trips$started_at)\rall_trips$month \u003c- format(as.Date(all_trips$date), \"%B\")\rall_trips$day \u003c- format(as.Date(all_trips$date), \"%d\")\rall_trips$year \u003c- format(as.Date(all_trips$date), \"%Y\")\rall_trips$day_of_week \u003c- format(as.Date(all_trips$date), \"%A\")\rall_trips$hour \u003c- lubridate::hour(all_trips$started_at)\rall_trips$ride_length \u003c- round(as.numeric(difftime(all_trips$ended_at,all_trips$started_at, units = \"mins\")),2)\rAdd column for seasons\nall_trips \u003c- all_trips %\u003e% mutate(season = recode(month,\rDecember = \"Winter\",\rJanuary = \"Winter\",\rFebruary = \"Winter\",\rMarch = \"Spring\",\rApril = \"Spring\",\rMay = \"Spring\",\rJune = \"Summer\",\rJuly = \"Summer\",\rAugust = \"Summer\",\rSeptember = \"Fall\",\rOctober = \"Fall\",\rNovember = \"Fall\"))\rAdd a column to represent the time of the day\nall_trips \u003c- all_trips %\u003e% mutate(time_of_day = case_when(\rhour \u003e= 6 \u0026 hour \u003c 9 ~ \"Early Morning\",\rhour \u003e= 9 \u0026 hour \u003c 12 ~ \"Mid Morning\",\rhour \u003e= 12 \u0026 hour \u003c 18 ~ \"Afternoon\",\rhour \u003e= 18 \u0026 hour \u003c= 23 ~ \"Evening\",\rhour \u003e= 0 \u0026 hour \u003c 3 ~ \"Early Night\",\rhour \u003e= 3 \u0026 hour \u003c 6 ~ \"Late Night\"))\rFind and address missing values\rCheck the user type and rideable type for missing values.\nall_trips %\u003e% filter(is.na(start_station_id)) %\u003e% count(start_station_id, start_station_name, rideable_type, member_casual)\r## # A tibble: 2 × 5\r## start_station_id start_station_name rideable_type member_casual n\r## ## 1 electric_bike casual 350065\r## 2 electric_bike member 493460\rThe missing values have been located in the electric_bike\nCreate new column to address missing values and also uniformize the longitude and latitude.\nall_trips \u003c- all_trips %\u003e% mutate(start_lat_round = round(start_lat, digits = 2),\rstart_lng_round = round(start_lng, digits = 2),\rend_lat_round = round(end_lat, digits = 2),\rend_lng_round = round(end_lng, digits = 2))\rFix missing station names and station ID\nall_trips \u003c- all_trips %\u003e% group_by(start_lat_round, start_lng_round) %\u003e% tidyr::fill(start_station_name, .direction = \"downup\") %\u003e% ungroup()\rall_trips \u003c- all_trips %\u003e% group_by(end_lat_round, end_lng_round) %\u003e% tidyr::fill(end_station_name, .direction = \"downup\") %\u003e% ungroup()\rall_trips \u003c- all_trips %\u003e% group_by(start_station_name) %\u003e% tidyr::fill(start_station_id, .direction = \"downup\") %\u003e% ungroup()\rall_trips \u003c- all_trips %\u003e% group_by(end_station_name) %\u003e% tidyr::fill(end_station_id, .direction = \"downup\") %\u003e% ungroup()\rCheck the data again to make sure the missing values have been fixed\ncolSums(is.na(all_trips))\r## ride_id rideable_type started_at ended_at ## 0 0 0 0 ## start_station_name start_station_id end_station_name end_station_id ## 11929 11929 40880 40880 ## start_lat start_lng end_lat end_lng ## 0 0 5899 5899 ## member_casual date month day ## 0 0 0 0 ## year day_of_week hour ride_length ## 0 0 0 0 ## season time_of_day start_lat_round start_lng_round ## 0 0 0 0 ## end_lat_round end_lng_round ## 5899 5899\rThese shows that some of the missing values can’t be fixed because they lack critical information, this will be handled by removing them from the dataframe. Their number are very small and insignificant so it can be disregarded.\nFind and clean “testing” or “repair” rides\rRides that are by the company employees for the purpose of testing or repairs are immaterial to the analysis being done and can actually skew the data. They will be isolated and eliminated.\nall_trips %\u003e% select(start_station_id) %\u003e% count(start_station_id) %\u003e% arrange(desc(n))\r## # A tibble: 1,312 × 2\r## start_station_id n\r## ## 1 13022 81578\r## 2 LF-005 46593\r## 3 TA1308000050 43541\r## 4 13042 42671\r## 5 13300 42225\r## 6 TA1307000039 38861\r## 7 13008 37142\r## 8 KA1503000014 36188\r## 9 13179 35857\r## 10 TA1308000001 35376\r## # … with 1,302 more rows\rall_trips %\u003e% select(end_station_id) %\u003e% count(end_station_id) %\u003e% arrange(desc(n))\r## # A tibble: 1,317 × 2\r## end_station_id n\r## ## 1 13022 81458\r## 2 LF-005 45159\r## 3 TA1308000050 44744\r## 4 13042 42189\r## 5 KA1503000014 42012\r## 6 13300 41533\r## 7 40880\r## 8 TA1307000039 38672\r## 9 13008 37270\r## 10 13179 36686\r## # … with 1,307 more rows\rFilter out the station related to testing and repair\nall_trips %\u003e% filter(start_station_id %in% c(\"DIVVY 001\", \"DIVVY 001 - Warehouse test station\", \"Hubbard Bike-checking (LBS-WH-TEST)\", \"Pawel Bialowas - Test- PBSC charging station\", \"DIVVY CASSETTE REPAIR MOBILE STATION\", \"2059 Hastings Warehouse Station\", \"Hastings WH 2\", \"Throop/Hastings Mobile Station\")) %\u003e%\rcount(start_station_id)\r## # A tibble: 6 × 2\r## start_station_id n\r## ## 1 2059 Hastings Warehouse Station 585\r## 2 DIVVY 001 77\r## 3 DIVVY 001 - Warehouse test station 14\r## 4 DIVVY CASSETTE REPAIR MOBILE STATION 7\r## 5 Hastings WH 2 14\r## 6 Hubbard Bike-checking (LBS-WH-TEST) 8124\rall_trips %\u003e% filter(end_station_id %in% c(\"DIVVY 001\", \"DIVVY 001 - Warehouse test station\", \"Hubbard Bike-checking (LBS-WH-TEST)\", \"Pawel Bialowas - Test- PBSC charging station\", \"DIVVY CASSETTE REPAIR MOBILE STATION\", \"2059 Hastings Warehouse Station\", \"Hastings WH 2\", \"Throop/Hastings Mobile Station\")) %\u003e% count(end_station_id)\r## # A tibble: 4 × 2\r## end_station_id n\r## ## 1 2059 Hastings Warehouse Station 791\r## 2 DIVVY CASSETTE REPAIR MOBILE STATION 7\r## 3 Hastings WH 2 167\r## 4 Hubbard Bike-checking (LBS-WH-TEST) 774\rremove data with unreasonable ride length\rRides that have a negative ride length will be treated as invalid, this is because the trip start time can’t be greater than the trip end time\rWhen the rides last more than a day (24hrs) it can be considered invalid because it is probably not being used, it was probably not docked after use.\rThe rides that are less than a minute (60s) are probably a docking mistake.\rall_trips \u003c- all_trips %\u003e% filter(ride_length \u003e= 1 \u0026 ride_length \u003c= 1440)\rRemoved data that were for the repair and testing station\rall_trips_v2 \u003c- all_trips %\u003e%\rfilter(!is.na(end_lat) \u0026 !is.na(end_lng))\rall_trips_v2 \u003c- all_trips_v2 %\u003e% filter(!start_station_id %in% c(\"DIVVY 001\", \"DIVVY 001 - Warehouse test station\", \"Hubbard Bike-checking (LBS-WH-TEST)\", \"Pawel Bialowas - Test- PBSC charging station\", \"DIVVY CASSETTE REPAIR MOBILE STATION\", \"2059 Hastings Warehouse Station\", \"Hastings WH 2\", \"Throop/Hastings Mobile Station\"))\rall_trips_v2 \u003c- all_trips_v2 %\u003e%\rfilter(!end_station_id %in% c(\"DIVVY 001\", \"DIVVY 001 - Warehouse test station\", \"Hubbard Bike-checking (LBS-WH-TEST)\", \"Pawel Bialowas - Test- PBSC charging station\", \"DIVVY CASSETTE REPAIR MOBILE STATION\", \"2059 Hastings Warehouse Station\", \"Hastings WH 2\", \"Throop/Hastings Mobile Station\"))\rRemoved the testing and repair stations and also renamed the new dataframe created.\ncheck the removed stations for accuracy\nstr(all_trips_v2)\r## tibble [5,612,878 × 26] (S3: tbl_df/tbl/data.frame)\r## $ ride_id : chr [1:5612878] \"E1E065E7ED285C02\" \"1602DCDC5B30FFE3\" \"BE7DD2AF4B55C4AF\" \"A1789BDF844412BE\" ...\r## $ rideable_type : chr [1:5612878] \"classic_bike\" \"classic_bike\" \"classic_bike\" \"classic_bike\" ...\r## $ started_at : POSIXct[1:5612878], format: \"2022-02-19 18:08:41\" \"2022-02-20 17:41:30\" ...\r## $ ended_at : POSIXct[1:5612878], format: \"2022-02-19 18:23:56\" \"2022-02-20 17:45:56\" ...\r## $ start_station_name: chr [1:5612878] \"State St \u0026 Randolph St\" \"Halsted St \u0026 Wrightwood Ave\" \"State St \u0026 Randolph St\" \"Southport Ave \u0026 Waveland Ave\" ...\r## $ start_station_id : chr [1:5612878] \"TA1305000029\" \"TA1309000061\" \"TA1305000029\" \"13235\" ...\r## $ end_station_name : chr [1:5612878] \"Clark St \u0026 Lincoln Ave\" \"Southport Ave \u0026 Wrightwood Ave\" \"Canal St \u0026 Adams St\" \"Broadway \u0026 Sheridan Rd\" ...\r## $ end_station_id : chr [1:5612878] \"13179\" \"TA1307000113\" \"13011\" \"13323\" ...\r## $ start_lat : num [1:5612878] 41.9 41.9 41.9 41.9 41.9 ...\r## $ start_lng : num [1:5612878] -87.6 -87.6 -87.6 -87.7 -87.6 ...\r## $ end_lat : num [1:5612878] 41.9 41.9 41.9 42 41.9 ...\r## $ end_lng : num [1:5612878] -87.6 -87.7 -87.6 -87.6 -87.6 ...\r## $ member_casual : chr [1:5612878] \"member\" \"member\" \"member\" \"member\" ...\r## $ date : Date[1:5612878], format: \"2022-02-19\" \"2022-02-20\" ...\r## $ month : chr [1:5612878] \"February\" \"February\" \"February\" \"February\" ...\r## $ day : chr [1:5612878] \"19\" \"20\" \"25\" \"14\" ...\r## $ year : chr [1:5612878] \"2022\" \"2022\" \"2022\" \"2022\" ...\r## $ day_of_week : chr [1:5612878] \"Saturday\" \"Sunday\" \"Friday\" \"Monday\" ...\r## $ hour : int [1:5612878] 18 17 18 11 5 9 10 20 13 7 ...\r## $ ride_length : num [1:5612878] 15.25 4.43 13.63 6.95 2.9 ...\r## $ season : chr [1:5612878] \"Winter\" \"Winter\" \"Winter\" \"Winter\" ...\r## $ time_of_day : chr [1:5612878] \"Evening\" \"Afternoon\" \"Evening\" \"Mid Morning\" ...\r## $ start_lat_round : num [1:5612878] 41.9 41.9 41.9 42 41.9 ...\r## $ start_lng_round : num [1:5612878] -87.6 -87.7 -87.6 -87.7 -87.6 ...\r## $ end_lat_round : num [1:5612878] 41.9 41.9 41.9 42 41.9 ...\r## $ end_lng_round : num [1:5612878] -87.6 -87.7 -87.6 -87.7 -87.6 ...\ris.factor(all_trips_v2$ride_length)\r## [1] FALSE\rall_trips_v2$ride_length \u003c- as.numeric(as.character(all_trips_v2$ride_length))\ris.numeric(all_trips_v2$ride_length)\r## [1] TRUE\rall_trips_v2%\u003e% select(start_station_id) %\u003e% count(start_station_id) %\u003e% arrange(desc(n))\r## # A tibble: 1,306 × 2\r## start_station_id n\r## ## 1 13022 79566\r## 2 LF-005 45310\r## 3 TA1308000050 42731\r## 4 13042 41847\r## 5 13300 41325\r## 6 TA1307000039 38115\r## 7 13008 36247\r## 8 KA1503000014 35531\r## 9 13179 35118\r## 10 TA1308000001 34776\r## # … with 1,296 more rows\rall_trips_v2%\u003e% select(end_station_id) %\u003e% count(end_station_id) %\u003e% arrange(desc(n))\r## # A tibble: 1,313 × 2\r## end_station_id n\r## ## 1 13022 79717\r## 2 LF-005 44366\r## 3 TA1308000050 43686\r## 4 13042 41423\r## 5 KA1503000014 41239\r## 6 13300 40734\r## 7 TA1307000039 37702\r## 8 13008 36598\r## 9 13179 35887\r## 10 TA1308000001 34615\r## # … with 1,303 more rows\rclass(all_trips_v2)\r## [1] \"tbl_df\" \"tbl\" \"data.frame\"\rcolSums(is.na(all_trips_v2))\r## ride_id rideable_type started_at ended_at ## 0 0 0 0 ## start_station_name start_station_id end_station_name end_station_id ## 11558 11558 33871 33871 ## start_lat start_lng end_lat end_lng ## 0 0 0 0 ## member_casual date month day ## 0 0 0 0 ## year day_of_week hour ride_length ## 0 0 0 0 ## season time_of_day start_lat_round start_lng_round ## 0 0 0 0 ## end_lat_round end_lng_round ## 0 0\rskim_without_charts(all_trips_v2)\rTable 1: Data summary\rName\rall_trips_v2\rNumber of rows\r5612878\rNumber of columns\r26\r_______________________\rColumn type frequency:\rcharacter\r13\rDate\r1\rnumeric\r10\rPOSIXct\r2\r________________________\rGroup variables\rNone\rVariable type: character\nskim_variable\rn_missing\rcomplete_rate\rmin\rmax\rempty\rn_unique\rwhitespace\rride_id\r0\r1.00\r16\r16\r0\r5612878\r0\rrideable_type\r0\r1.00\r11\r13\r0\r3\r0\rstart_station_name\r11558\r1.00\r9\r64\r0\r1671\r0\rstart_station_id\r11558\r1.00\r3\r37\r0\r1305\r0\rend_station_name\r33871\r0.99\r9\r64\r0\r1688\r0\rend_station_id\r33871\r0.99\r3\r37\r0\r1312\r0\rmember_casual\r0\r1.00\r6\r6\r0\r2\r0\rmonth\r0\r1.00\r3\r9\r0\r12\r0\rday\r0\r1.00\r2\r2\r0\r31\r0\ryear\r0\r1.00\r4\r4\r0\r2\r0\rday_of_week\r0\r1.00\r6\r9\r0\r7\r0\rseason\r0\r1.00\r4\r6\r0\r4\r0\rtime_of_day\r0\r1.00\r7\r13\r0\r6\r0\rVariable type: Date\nskim_variable\rn_missing\rcomplete_rate\rmin\rmax\rmedian\rn_unique\rdate\r0\r1\r2022-02-01\r2023-01-31\r2022-07-27\r365\rVariable type: numeric\nskim_variable\rn_missing\rcomplete_rate\rmean\rsd\rp0\rp25\rp50\rp75\rp100\rstart_lat\r0\r1\r41.90\r0.05\r41.64\r41.88\r41.90\r41.93\r42.07\rstart_lng\r0\r1\r-87.65\r0.03\r-87.84\r-87.66\r-87.64\r-87.63\r-87.52\rend_lat\r0\r1\r41.90\r0.07\r0.00\r41.88\r41.90\r41.93\r42.37\rend_lng\r0\r1\r-87.65\r0.10\r-88.14\r-87.66\r-87.64\r-87.63\r0.00\rhour\r0\r1\r14.21\r5.03\r0.00\r11.00\r15.00\r18.00\r23.00\rride_length\r0\r1\r16.46\r28.68\r1.00\r6.02\r10.43\r18.58\r1439.37\rstart_lat_round\r0\r1\r41.90\r0.05\r41.64\r41.88\r41.90\r41.93\r42.07\rstart_lng_round\r0\r1\r-87.65\r0.03\r-87.84\r-87.66\r-87.64\r-87.63\r-87.52\rend_lat_round\r0\r1\r41.90\r0.07\r0.00\r41.88\r41.90\r41.93\r42.37\rend_lng_round\r0\r1\r-87.65\r0.10\r-88.14\r-87.66\r-87.64\r-87.63\r0.00\rVariable type: POSIXct\nskim_variable\rn_missing\rcomplete_rate\rmin\rmax\rmedian\rn_unique\rstarted_at\r0\r1\r2022-02-01 00:03:18\r2023-01-31 23:56:09\r2022-07-27 19:51:47\r4724012\rended_at\r0\r1\r2022-02-01 00:09:37\r2023-02-01 00:28:12\r2022-07-27 20:10:25\r4736481\rAnalysis and Visualization of the Data\rAnalyzing the data in order to get different insights from it in different ways. Focusing on analyzing how the annual member riders and the casual riders use Cyclistic bikes differently.\nSummary\rGet the summary of the data to be used for analysis in order to get a snapshot of the information.\nsummary(all_trips_v2)\r## ride_id rideable_type started_at ## Length:5612878 Length:5612878 Min. :2022-02-01 00:03:18.00 ## Class :character Class :character 1st Qu.:2022-06-02 12:16:51.50 ## Mode :character Mode :character Median :2022-07-27 19:51:47.50 ## Mean :2022-07-29 10:10:19.89 ## 3rd Qu.:2022-09-22 19:13:23.50 ## Max. :2023-01-31 23:56:09.00 ## ended_at start_station_name start_station_id ## Min. :2022-02-01 00:09:37.00 Length:5612878 Length:5612878 ## 1st Qu.:2022-06-02 12:36:19.00 Class :character Class :character ## Median :2022-07-27 20:10:25.00 Mode :character Mode :character ## Mean :2022-07-29 10:26:47.51 ## 3rd Qu.:2022-09-22 19:28:37.00 ## Max. :2023-02-01 00:28:12.00 ## end_station_name end_station_id start_lat start_lng ## Length:5612878 Length:5612878 Min. :41.64 Min. :-87.84 ## Class :character Class :character 1st Qu.:41.88 1st Qu.:-87.66 ## Mode :character Mode :character Median :41.90 Median :-87.64 ## Mean :41.90 Mean :-87.65 ## 3rd Qu.:41.93 3rd Qu.:-87.63 ## Max. :42.07 Max. :-87.52 ## end_lat end_lng member_casual date ## Min. : 0.00 Min. :-88.14 Length:5612878 Min. :2022-02-01 ## 1st Qu.:41.88 1st Qu.:-87.66 Class :character 1st Qu.:2022-06-02 ## Median :41.90 Median :-87.64 Mode :character Median :2022-07-27 ## Mean :41.90 Mean :-87.65 Mean :2022-07-28 ## 3rd Qu.:41.93 3rd Qu.:-87.63 3rd Qu.:2022-09-22 ## Max. :42.37 Max. : 0.00 Max. :2023-01-31 ## month day year day_of_week ## Length:5612878 Length:5612878 Length:5612878 Length:5612878 ## Class :character Class :character Class :character Class :character ## Mode :character Mode :character Mode :character Mode :character ## ## ## ## hour ride_length season time_of_day ## Min. : 0.00 Min. : 1.00 Length:5612878 Length:5612878 ## 1st Qu.:11.00 1st Qu.: 6.02 Class :character Class :character ## Median :15.00 Median : 10.43 Mode :character Mode :character ## Mean :14.21 Mean : 16.46 ## 3rd Qu.:18.00 3rd Qu.: 18.58 ## Max. :23.00 Max. :1439.37 ## start_lat_round start_lng_round end_lat_round end_lng_round ## Min. :41.64 Min. :-87.84 Min. : 0.00 Min. :-88.14 ## 1st Qu.:41.88 1st Qu.:-87.66 1st Qu.:41.88 1st Qu.:-87.66 ## Median :41.90 Median :-87.64 Median :41.90 Median :-87.64 ## Mean :41.90 Mean :-87.65 Mean :41.90 Mean :-87.65 ## 3rd Qu.:41.93 3rd Qu.:-87.63 3rd Qu.:41.93 3rd Qu.:-87.63 ## Max. :42.07 Max. :-87.52 Max. :42.37 Max. : 0.00\rComparism of Member riders to Casual Riders\rStarting off with numbers and percentage comparison\nall_trips_v2%\u003e% group_by(member_casual) %\u003e% summarise(count = n(), Percentage = n()/nrow(all_trips_v2)*100)\r## # A tibble: 2 × 3\r## member_casual count Percentage\r## ## 1 casual 2284633 40.7\r## 2 member 3328245 59.3\rAnalysis\nDuring the time frame studied for this analysis (12 month period), 40.7% of the riders that used the rideables were casual riders while about 59.3% of the riders in the same time period were member riders. Converting a portion of the casual riders to members would be very advantageous.\nVisualizing by member type\nggplot(all_trips_v2, aes(member_casual, fill=member_casual)) +\rgeom_bar() +\rlabs(x=\"User Type\", y=\"Count\", title = \"Total Rides: Casual vs Member\") +\rannotate(\"text\",x=1,y=2000000,label=\"2,284,633 / (40.7%)\",color=\"black\",size=3.5) +\rannotate(\"text\",x=2,y=3000000,label=\"3,328,245 / (59.3%)\",color=\"black\",size=3.5) A majority of the riders (59.3%) are members while the rest (40.7%) are casual riders.\nVisualizing the total rides by the user type and rideable type\nall_trips_v2%\u003e% group_by(member_casual, rideable_type) %\u003e% summarise(count = n()) %\u003e% ggplot(aes(x=member_casual, y=count, fill=rideable_type)) + geom_bar(stat=\"identity\", width = 0.3) +\rlabs(x=\"Rideable Type\", y=\"Number of Rides\", title = \"Total Rides by user type and rideable type\")\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rThe members riders slightly favor the classic bike over the electric bike:\r- Most casual riders use electric bikes\r- members don’t use docked bikes\r- members use both classic and electric bikes almost equally\nAnalyzing the length of rides\rsummary(all_trips_v2$ride_length)\r## Min. 1st Qu. Median Mean 3rd Qu. Max. ## 1.00 6.02 10.43 16.46 18.58 1439.37\rThe minimum ride length is 1 minute, which is expected due to cleaning\rAverage of all ride lengths is 16.46 minutes\rThe average length of ride for each trip (in minutes) by the type of user\naggregate(all_trips_v2$ride_length~all_trips_v2$member_casual, FUN = mean)\r## all_trips_v2$member_casual all_trips_v2$ride_length\r## 1 casual 22.10731\r## 2 member 12.58425\rAnalysis\rThe casual riders rode the bikes for significantly more time on average than the member riders.\nBreaking down ride lengths for more analysis\nall_trips_v2%\u003e% group_by(member_casual) %\u003e% summarize(\"\u003c=5min\" = sum(ride_length \u003c=5),\r\"\u003c=15min\" = sum(ride_length \u003c=15),\r\"\u003c=30min\" = sum(ride_length \u003c=30),\r\"\u003c=45min\" = sum(ride_length \u003c=45),\r\"\u003c=60min\" = sum(ride_length \u003c=60),\r\"\u003e2hrs\" = sum(ride_length \u003e120),\r\"\u003e4hrs\" = sum(ride_length \u003e240),\r\"\u003e6hrs\" = sum(ride_length \u003e360),)\r## # A tibble: 2 × 9\r## member_casual `\u003c=5min` \u003c=15m…¹ \u003c=30m…² \u003c=45m…³ \u003c=60m…⁴ `\u003e2hrs` `\u003e4hrs` `\u003e6hrs`\r## ## 1 casual 266189 1278389 1863455 2057141 2142989 33432 5731 3206\r## 2 member 757992 2462997 3116478 3273578 3305079 5982 2111 1218\r## # … with abbreviated variable names ¹​`\u003c=15min`, ²​`\u003c=30min`, ³​`\u003c=45min`,\r## # ⁴​`\u003c=60min`\rAnalysis\rThis shows that for both user types, the vast majority of ride length is below 60 minutes, more data would be needed to analyze this trend but I suspect that it’s the maximum endurance of non professional riders. And distances beyond this point most riders will choose another mode of transportation. Perhaps an availability of more electric bikes would encourage longer rides.\nall_trips_v2 %\u003e% group_by(member_casual) %\u003e% summarize(\"\u003c10 min\" = sum(ride_length \u003c9.99),\r\"10-20 min\" = sum(ride_length \u003e=10 \u0026 ride_length \u003c=19.99),\r\"20-30 min\" = sum(ride_length \u003e=20 \u0026 ride_length \u003c=29.99),\r\"30-60 min\" = sum(ride_length \u003e=30 \u0026 ride_length \u003c=59.99),\r\"60-120 min\" = sum(ride_length \u003e=60 \u0026 ride_length \u003c=119.99),\r\"120-240 min\" = sum(ride_length \u003e=120 \u0026 ride_length \u003c=239.99),\r\"240+min\" = sum(ride_length \u003e=240))\r## # A tibble: 2 × 8\r## member_casual `\u003c10 min` `10-20 min` 20-30 mi…¹ 30-60…² 60-12…³ 120-2…⁴ 240+m…⁵\r## ## 1 casual 845416 707829 309833 279832 108280 27712 5731\r## 2 member 1844513 954711 316957 188886 17195 3872 2111\r## # … with abbreviated variable names ¹​`20-30 min`, ²​`30-60 min`, ³​`60-120 min`,\r## # ⁴​`120-240 min`, ⁵​`240+min`\rAnalysis\rThis shows that casual riders tend to keep the rideables for much longer than member riders, but the members tend to take shorter rides.\nall_trips_v3 \u003c- all_trips_v2%\u003e% mutate(ride_length_grp = case_when(\rride_length \u003c9.99 ~ \"\u003c 10 min\",\rride_length \u003e=10 \u0026 ride_length \u003c=19.99 ~ \"10-20 min\",\rride_length \u003e=20 \u0026 ride_length \u003c=29.99 ~ \"20-30 min\",\rride_length \u003e=30 \u0026 ride_length \u003c=59.99 ~ \"30-60 min\",\rride_length \u003e=60 \u0026 ride_length \u003c=119.99 ~ \"60-120 min\",\rride_length \u003e=120 \u0026 ride_length \u003c=239.99 ~ \"120-240 min\",\rride_length \u003e=240 ~ \"240+ min\"))\rall_trips_v3 %\u003e% group_by(member_casual, ride_length_grp) %\u003e% summarise(count = n()) %\u003e% ggplot(aes(x=factor(ride_length_grp, level = c(\"\u003c 10 min\", \"10-20 min\", \"20-30 min\", \"30-60 min\",\r\"60-120 min\", \"120-240 min\", \"240+ min\")), y=count, fill=member_casual)) + geom_col(position = \"dodge\") +\rlabs(x=\"Ride Length\", y=\"Number of Rides\", title = \"Total Rides by user type and ride length grouping\")\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\rMost of the rides fall within the 1 to 20 minutes ride length in minutes, this information can be further enhanced by obtaining survey information on riding behaviors.\nLooking at the average ride length of each trip (in minutes) based on user type and the hour of day\nall_trips_v3 %\u003e% group_by(member_casual, hour) %\u003e% summarise(count = n(), average_ride_length=mean(ride_length)) %\u003e% arrange(member_casual, hour) %\u003e% ggplot(aes(x=factor(hour, level= c(6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4,5)), y=average_ride_length, fill=member_casual)) + geom_col(position = \"dodge\") +\rlabs(x=\"Hour of day\", y=\"Ride Length (in minutes)\", title = \"Average ride length by user type and hour of the day\")\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\rThe casual riders had on average longer rides than member riders peaking between 10AM - 3PM, while member riders stayed relatively constant throughout the day.This insight can be useful in planning maintenance times for the rideables.\naxis_labels \u003c- c(\"Early Morning \\n6am-9am\", \"Mid Morning \\n9am-12pm\", \"Afternoon \\n12pm-6pm\", \"Evening \\n6pm-11pm\", \"Early Night \\n11pm-3am\", \"Wee Night \\n3am-6am\")\rall_trips_v3 %\u003e% group_by(member_casual, time_of_day) %\u003e% summarise(count = n(), average_ride_length=mean(ride_length)) %\u003e% ggplot(aes(x=factor(time_of_day, level= c(\"Early Morning\", \"Mid Morning\", \"Afternoon\", \"Evening\", \"Early Night\", \"Late Night\")), y=average_ride_length, fill=member_casual)) + geom_col(position = \"dodge\", width = 0.4) +\rlabs(x=\"Time of Day\", y=\"Ride Length (minutes)\", title = \"Average ride length by user type and time of the day\") +\rscale_x_discrete(labels = axis_labels)\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\nThe length of the bike ride for the casual riders peaks during the mid morning through the afternoon\rThe length of the bike ride for member riders remains more constant throughout the day\raggregate(all_trips_v3$ride_length ~ all_trips_v3$member_casual + all_trips_v3$day_of_week, FUN = mean)\r## all_trips_v3$member_casual all_trips_v3$day_of_week all_trips_v3$ride_length\r## 1 casual Friday 20.71813\r## 2 member Friday 12.39689\r## 3 casual Monday 22.55896\r## 4 member Monday 12.15048\r## 5 casual Saturday 24.84920\r## 6 member Saturday 14.04720\r## 7 casual Sunday 25.31523\r## 8 member Sunday 13.92415\r## 9 casual Thursday 19.70325\r## 10 member Thursday 12.16705\r## 11 casual Tuesday 19.76585\r## 12 member Tuesday 11.94311\r## 13 casual Wednesday 19.07947\r## 14 member Wednesday 11.99994\rall_trips_v3 %\u003e% group_by(member_casual, day_of_week) %\u003e% summarise(count = n(), average_ride_length=mean(ride_length)) %\u003e% ggplot(aes(x=factor(day_of_week, level= c(\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\", \"Sunday\")), y=average_ride_length, fill=member_casual)) + geom_col(position = \"dodge\", width = 0.4) + labs(x=\"Day of Week\", y=\"Ride Length ( minutes)\", title = \"Average ride length by the user type and day of the week\")\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\nThe weekends saw increased bike use by minutes for both user types, casual riders were consistent throughout the week up until Saturday which is their preferred day of week. Meanwhile, the member riders looked to have a consistent weekly ride and a small weekend spike on the weekend for their bike use. The most popular day for minutes used for both user types is on Sundays.\nall_trips_v3 %\u003e% group_by(member_casual, hour) %\u003e% summarise(count = n()) %\u003e% arrange(member_casual, hour) %\u003e% ggplot(aes(x=factor(hour, level= c(6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4,5)), y=count, fill=member_casual)) + geom_col(position = \"dodge\") +\rlabs(x=\"Hour of the day\", y=\"Number of Rides\", title = \"Total Rides by user type and hour of the day\")\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\nThe member riders show an increased use of rideables starting from 6am and peaking at 8am and they see another peak from 4pm to 6pm.\rThe Casual riders only peak from 4pm to 6 pm.\rall_trips_v3 %\u003e% group_by(member_casual) %\u003e% summarize(\"Early Morning\" = sum(time_of_day == \"Early Morning\"),\r\"Mid Morning\" = sum(time_of_day == \"Mid Morning\"),\r\"Afternoon\" = sum(time_of_day == \"Afternoon\"),\r\"Evening\" = sum(time_of_day == \"Evening\"),\r\"Early Night\" = sum(time_of_day == \"Early Night\"),\r\"Late Night\" = sum(time_of_day == \"Late Night\"))\r## # A tibble: 2 × 7\r## member_casual `Early Morning` `Mid Morning` Afternoon Evening Early …¹ Late …²\r## ## 1 casual 150178 282434 1034339 694212 92950 30520\r## 2 member 470104 440497 1412537 885751 70557 48799\r## # … with abbreviated variable names ¹​`Early Night`, ²​`Late Night`\rall_trips_v3 %\u003e% group_by(member_casual, time_of_day) %\u003e% summarise(count = n()) %\u003e% ggplot(aes(x=factor(time_of_day, level= c(\"Early Morning\", \"Mid Morning\", \"Afternoon\", \"Evening\", \"Early Night\", \"Late Night\")), y=count, fill=member_casual)) + geom_col(position = \"dodge\", width = 0.4) + labs(x=\"Time of the Day\", y=\"Number of Rides\", title = \"Total Rides by user type and time of the day\") +\rscale_x_discrete(labels = axis_labels)\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\nMember riders out use the causal riders at all times except for during the early night\rAfternoon and evening saw the biggest number of rides for both membership types\rall_trips_v3 %\u003e% group_by(member_casual, time_of_day) %\u003e% summarise(count = n()) %\u003e% ggplot(aes(x=factor(time_of_day, level= c(\"Early Morning\", \"Mid Morning\", \"Afternoon\", \"Evening\", \"Early Night\", \"Late Night\")), y=count, color=member_casual)) + geom_point() + geom_line(aes(group = member_casual)) +\rlabs(x=\"Time of the Day\", y=\"Number of Rides\", title = \"Total Rides by user type and time of the day\") + ylim(0, NA) +\rscale_x_discrete(labels = axis_labels)\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\nThis follows the trends previously noticed, with peak times, suggestion that maintenance should be done outside of peak hours in order to main rideable availability and create customer satisfaction.\nAnalysis of total rides based on user type and day of the week\rall_trips_v3 %\u003e% group_by(member_casual) %\u003e% summarize(\"Monday\" = sum(day_of_week == \"Monday\"),\r\"Tuesday\" = sum(day_of_week == \"Tuesday\"),\r\"Wednesday\" = sum(day_of_week == \"Wednesday\"),\r\"Thursday\" = sum(day_of_week == \"Thursday\"),\r\"Friday\" = sum(day_of_week == \"Friday\"),\r\"Saturday\" = sum(day_of_week == \"Saturday\"),\r\"Sunday\" = sum(day_of_week == \"Sunday\"))\r## # A tibble: 2 × 8\r## member_casual Monday Tuesday Wednesday Thursday Friday Saturday Sunday\r## ## 1 casual 273930 261419 271058 304027 328728 462513 382958\r## 2 member 471235 521864 523339 527774 464289 435606 384138\rall_trips_v3 %\u003e% group_by(member_casual, day_of_week) %\u003e% summarise(count = n()) %\u003e% ggplot(aes(x=factor(day_of_week, level= c(\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\", \"Sunday\")), y=count, fill=member_casual)) + geom_col(position = \"dodge\", width = 0.4) + labs(x=\"Day of the Week\", y=\"Number of Rides\", title = \"Total Rides by user type and day of the week\")\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\nThe member riders use more rideables during the week while the casual riders use more rideables during the weekends.\nall_trips_v3 %\u003e% group_by(member_casual, day_of_week) %\u003e% summarise(count = n()) %\u003e% ggplot(aes(x=factor(day_of_week, level= c(\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\", \"Sunday\")), y=count, color=member_casual)) + geom_point() + geom_line(aes(group = member_casual)) +\rlabs(x=\"Day of Week\", y=\"Number of Rides\", title = \"Total Rides by user type and day of the week\") +\rylim(0, NA)\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rThe analysis of the total rides by the type of user and the season\rall_trips_v3 %\u003e% group_by(member_casual, season) %\u003e% summarise(count = n()) %\u003e% ggplot(aes(x=factor(season, level= c(\"Spring\", \"Summer\", \"Fall\", \"Winter\")), y=count, fill=member_casual)) + geom_col(position = \"dodge\", width = 0.4) + labs(x=\"Season of the Year\", y=\"Number of Rides\", title = \"Total Rides by user type and season of the year\")\r## `summarise()` has grouped output by 'member_casual'. You can override using the\r## `.groups` argument.\rAnalysis\rSummer saw the highest rideable use and the winter saw the lowest rideable use, this is probably due to the weather. There is little that can be done to mitigate this but heated bikes is an avenue worth exploring.\nall_trips_v3 %\u003e% filter(!(is.na(start_station_name))) %\u003e% filter(member_casual == \"casual\") %\u003e% group_by(start_station_name) %\u003e% summarize(count=n()) %\u003e% arrange(-count) %\u003e% top_n(10)\r## Selecting by count\r## # A tibble: 10 × 2\r## start_station_name count\r## ## 1 Streeter Dr \u0026 Grand Ave 61066\r## 2 DuSable Lake Shore Dr \u0026 Monroe St 31809\r## 3 Michigan Ave \u0026 Oak St 26456\r## 4 DuSable Lake Shore Dr \u0026 North Blvd 26386\r## 5 Millennium Park 26308\r## 6 Shedd Aquarium 20493\r## 7 Theater on the Lake 19651\r## 8 Wells St \u0026 Concord Ln 18923\r## 9 Clark St \u0026 Lincoln Ave 18419\r## 10 Dusable Harbor 16228\rall_trips_v3 %\u003e% filter(!(is.na(start_station_name))) %\u003e% filter(member_casual == \"casual\") %\u003e% group_by(start_station_name) %\u003e% summarize(count=n()) %\u003e% arrange(-count) %\u003e% top_n(10) %\u003e% mutate(start_station_name= fct_reorder(start_station_name, count)) %\u003e% ggplot(aes(x=start_station_name, y=count, fill=count)) +\rgeom_bar(stat = \"identity\") +\rcoord_flip() +\rlabs(x=\"Number of Rides\", y=\"Name of Start Station \", title=\"Top 10 starting stations for casual riders\")\r## Selecting by count\rall_trips_v3 %\u003e% filter(!(is.na(end_station_name))) %\u003e% filter(member_casual == \"casual\") %\u003e% group_by(end_station_name) %\u003e% summarize(count=n()) %\u003e% arrange(-count) %\u003e% top_n(10)\r## Selecting by count\r## # A tibble: 10 × 2\r## end_station_name count\r## ## 1 Streeter Dr \u0026 Grand Ave 63523\r## 2 DuSable Lake Shore Dr \u0026 Monroe St 30126\r## 3 Millennium Park 27700\r## 4 DuSable Lake Shore Dr \u0026 North Blvd 27217\r## 5 Michigan Ave \u0026 Oak St 27198\r## 6 Theater on the Lake 20663\r## 7 Clark St \u0026 Lincoln Ave 19096\r## 8 Wells St \u0026 Concord Ln 18814\r## 9 Shedd Aquarium 18584\r## 10 Dusable Harbor 15474\rall_trips_v3 %\u003e% filter(!(is.na(start_station_name))) %\u003e% filter(member_casual == \"member\") %\u003e% group_by(start_station_name) %\u003e% summarize(count=n()) %\u003e% arrange(-count) %\u003e% top_n(10)\r## Selecting by count\r## # A tibble: 10 × 2\r## start_station_name count\r## ## 1 Ellis Ave \u0026 60th St 29268\r## 2 Kingsbury St \u0026 Kinzie St 25303\r## 3 University Ave \u0026 57th St 25261\r## 4 Ellis Ave \u0026 55th St 24845\r## 5 Clark St \u0026 Elm St 23954\r## 6 Wells St \u0026 Concord Ln 23808\r## 7 Clinton St \u0026 Washington Blvd 21257\r## 8 Wells St \u0026 Elm St 20687\r## 9 Loomis St \u0026 Lexington St 19920\r## 10 Broadway \u0026 Barry Ave 19672\rall_trips_v3 %\u003e% filter(!(is.na(start_station_name))) %\u003e% filter(member_casual == \"member\") %\u003e% group_by(start_station_name) %\u003e% summarize(count=n()) %\u003e% arrange(-count) %\u003e% top_n(10) %\u003e% mutate(start_station_name= fct_reorder(start_station_name, count)) %\u003e% ggplot(aes(x=start_station_name, y=count, fill=count)) +\rgeom_bar(stat = \"identity\") +\rcoord_flip() +\rlabs(x=\"Number of Rides\", y=\"Name of Start Station \", title=\"Top 10 starting stations for member riders\")\r## Selecting by count\rall_trips_v3 %\u003e% filter(!(is.na(end_station_name))) %\u003e% filter(member_casual == \"member\") %\u003e% group_by(end_station_name) %\u003e% summarize(count=n()) %\u003e% arrange(-count) %\u003e% top_n(10)\r## Selecting by count\r## # A tibble: 10 × 2\r## end_station_name count\r## ## 1 Ellis Ave \u0026 60th St 34214\r## 2 Kingsbury St \u0026 Kinzie St 25718\r## 3 University Ave \u0026 57th St 25095\r## 4 Wells St \u0026 Concord Ln 24872\r## 5 Clark St \u0026 Elm St 24082\r## 6 Ellis Ave \u0026 55th St 22564\r## 7 Clinton St \u0026 Washington Blvd 22176\r## 8 Clinton St \u0026 Madison St 19623\r## 9 Broadway \u0026 Barry Ave 19552\r## 10 Loomis St \u0026 Lexington St 19219\rAnalysis\nThe information on the top 10 end and start station for both riders can be used to determine availability of rideables.\nExport file for more analysis\rwrite_csv(all_trips_v3, file = \"all_trips_v3.csv\")\rConclusion\rThe first phenomenon that is easily noticeable is the stark difference between casual riders and riders with membership subscriptions, there is a significant difference in length of ride between both sets of riders.\nKey Findings\rApart from the weekends (Saturday and Sunday) the ride length of the member riders remained relatively unchanged.\nThere is a slight uptick (about 16%) in member riders’ length of rides on weekends, it starts on Friday and experiences a sharp drop on Monday. It remains relatively the same until Friday again.\nThe ride length for casual riders changed significantly from day to day with the peek coming on weekends (Saturday and Sunday).\nThere is a visible inverse bell curve for the ride length of the casual riders, from the beginning of the week (Sunday) to the end of the week (Saturday). There is a dip in midweek and then a steady climb until the weekend, then a slow drop after the weekend.\nComparing the casual riders to the member riders, there is a doubling (100% increase) in ride length from the member riders to the casual riders. This means that for any giving day of the week the casual riders have twice the ride time of the member riders.\nBusiness Task Questions\rHow do annual members and casual riders use Cyclistic bikes differently?\rWhy would casual riders buy Cyclistic annual memberships?\rHow can Cyclistic use digital media to influence casual riders to become members?\rChallenges\nThe lack of individual rider identifiers which would have been integral in deciphering the ride patterns of casual riders would have been quite useful. Finding out if the casual riders were repeat users or just one-time users would have been beneficial.\nConvincing casual riders to buy annual memberships\rGiven the information analyzed, the following steps can be deployed to increase annual membership among casual riders:\nIf the cost to rent for a day or 2 is lower than the weekly cost of membership then the cost of a one-day usage should be increased, this would encourage weekend users to subscribe.\rOffer different types of memberships to cater to different types of riders, for example a weekend pass can be offered to capitalize on the weekend spike. The weekday pass can be made cheaper than the weekend pass to encourage weekday casual users.\rOffer members only exclusives with the rides, an example will be bikes reserved for members only, priority bike usage over the weekend due to increased demands\rRun an ad campaign to showcase the benefits of a membership, explain the pricing and the benefits\rOffer a discount if the whole annual membership fee was paid all at once instead of monthly, also offer auto-pay capabilities and make payment as seamless as possible by offering different pay types.\rExplore charging casual riders by the hour, while members are given unlimited ride time\rOverall, more insight could be provided if more data is available, especially individual ride identities. I’m positive that these recommendations provided would convince casual riders to subscribe to a membership, which in turn will lead to increased revenue.\n","wordCount":"7997","inLanguage":"en","datePublished":"2023-07-15T00:00:00Z","dateModified":"2023-07-15T00:00:00Z","author":{"@type":"Person","name":"Nnamdi Okoli"},"mainEntityOfPage":{"@type":"WebPage","@id":"/portfolio/cyclistic-bike/"},"publisher":{"@type":"Organization","name":"Nnamdi Okoli","logo":{"@type":"ImageObject","url":"favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href accesskey=h title="Nnamdi Okoli (Alt + H)"><img src=img/icon.png alt aria-label=logo height=35>Nnamdi Okoli</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=/about/ title=About><span>About</span></a></li><li><a href=/portfolio/ title=Portfolio><span>Portfolio</span></a></li><li><a href=/skills/ title=Skills><span>Skills</span></a></li><li><a href=/tags/ title=Tags><span>Tags</span></a></li><li><a href=/search/ title="Search (Alt + /)" accesskey=/><span>Search</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href>Home</a>&nbsp;»&nbsp;<a href=/portfolio/>Portfolios</a></div><h1 class=post-title>Cyclistic Bike-Share Case Study</h1><div class=post-meta><span title='2023-07-15 00:00:00 +0000 UTC'>July 15, 2023</span>&nbsp;·&nbsp;38 min&nbsp;·&nbsp;Nnamdi Okoli</div></header><div class=post-content><div id=table-of-contents class="section level1"><h1><strong>Table of Contents</strong></h1></div><div id=scenario class="section level1"><h1><strong>Scenario</strong></h1><p>In this case, I am assuming the role of a junior data analyst working in the marketing and analytics team at Cyclistic, a bike-share company in Chicago with two types of customers. The director of marketing believes the company’s future success depends on maximizing the number of annual memberships. Customers who buy single-ride or full-day passes are known as casual riders, while the customers who purchase annual memberships are known as members. Therefore, the team wants to understand how casual riders and annual members use Cyclistic bikes differently. From these insights, the team will design a new marketing strategy to convert casual riders into annual members. But first, Cyclistic executives must approve the recommendations, so they must be backed up with compelling data insights and professional data visualizations.
Characters and teams.</p></div><div id=asking-questions-and-problem-definition class="section level1"><h1><strong>Asking questions and problem definition</strong></h1><div id=ask-the-right-questions class="section level2"><h2>Ask the right questions</h2><p>In this step, I asked myself questions such as ‘How do annual members and casual riders use Cyclistic bikes differently?’ to guide my analysis. Lily Moreno believes that the annual Members were more profitable than the casual riders. The goal before me is to assist the marketing team analyze the contrast between casual riders and members with the aim of providing recommendations that will aid the conversion of casual riders into annual members to maximize profits.</p><ol style=list-style-type:lower-alpha><li>How do annual members and casual riders use Cyclistic bikes differently?</li><li>Why would casual riders buy Cyclistic annual memberships?</li><li>How can Cyclistic use digital media to influence casual riders to become members?</li></ol></div><div id=identify-the-business-task class="section level2"><h2>Identify the business task</h2><p>A bike-share program that features more than 5,800 bicycles and 600 docking stations. Cyclistic sets itself apart by also offering reclining bikes, hand tricycles, and cargo bikes, making bike-share more inclusive to people with disabilities and riders who can’t use a standard two-wheeled bike. The majority of riders opt for traditional bikes; about 8% of riders use the assistive options. Cyclistic users are more likely to ride for leisure, but about 30% use them to commute to work each day.</p></div><div id=identifying-key-stakeholders class="section level2"><h2>Identifying key stakeholders</h2><p><strong>Lily Moreno:</strong> The director of marketing and your manager. Moreno is responsible for the development of campaigns and initiatives to promote the bike-share program. These may include email, social media, and other channels.</p><p><strong>Cyclistic marketing analytics team:</strong> A team of data analysts who are responsible for collecting, analyzing, and reporting data that helps guide Cyclistic marketing strategy. You joined this team six months ago and have been busy learning about Cyclistic’s mission and business goals — as well as how you, as a junior data analyst, can help Cyclistic achieve them.</p><p><strong>Cyclistic executive team:</strong> The notoriously detail-oriented executive team will decide whether to approve the recommended marketing program</p></div><div id=approach class="section level2"><h2>Approach</h2><p>Data analysis is a crucial step in solving problems. It is the process of collecting, organizing, and interpreting data to answer questions and reach conclusions. By analyzing data, businesses, organizations, and individuals can identify patterns and trends that can help them make informed decisions and improve their performance. This will involve sorting the data into categories and performing calculations or visualizing it with charts and graphs. I will also examine the data for any outliers or inconsistencies that may indicate a problem. After the data has been analyzed, it is important to interpret the results. This involves examining the data to identify any patterns or trends that may be present. It is also important to consider any potential causes of the problem, such as internal processes or external factors.</p></div></div><div id=prepare-the-data class="section level1"><h1><strong>Prepare the data</strong></h1><p>The data used for this analysis is located at (<a href=https://divvy-tripdata.s3.amazonaws.com/index.html class=uri>https://divvy-tripdata.s3.amazonaws.com/index.html</a>), The data is made available under this (<a href=https://ride.divvybikes.com/data-license-agreement class=uri>https://ride.divvybikes.com/data-license-agreement</a>) I downloaded the most recent 12 months from February 2022 to January 2023 and stored them locally. This version of my analysis was done using R, spreadsheet, and Tableau. The dataset has no user ID or any specific commuter identifier, so the data on duplicate riders are not present.</p><div id=sort-and-filter-the-data-in-a-spreasheet class="section level2"><h2>Sort and filter the data in a spreasheet</h2><ul><li>I checked for incomplete values in all columns</li><li>I checked for duplicate values</li><li>I checked for outliers</li></ul></div><div id=utilize-r-and-rstudio class="section level2"><h2>Utilize R and RStudio</h2><p>Given the size of the dataset after inspection with Excel, I decided on using R for analysis and specifically R studio.</p></div><div id=loaded-the-packages class="section level2"><h2>Loaded the packages</h2><pre class=r><code>library(tidyverse)
library(ggplot2)
library(lubridate)
library(skimr)</code></pre></div><div id=upload-the-data-files-and-create-data-frames class="section level2"><h2>Upload the data files and create data frames</h2><pre class=r><code>feb_2022 &lt;- read_csv(&quot;2022_02-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 115609 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>mar_2022 &lt;- read_csv(&quot;2022_03-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 284042 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>apr_2022 &lt;- read_csv(&quot;2022_04-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 371249 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>may_2022 &lt;- read_csv(&quot;2022_05-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 634858 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>jun_2022 &lt;- read_csv(&quot;2022_06-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 769204 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>jul_2022 &lt;- read_csv(&quot;2022_07-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 823488 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>aug_2022 &lt;- read_csv(&quot;2022_08-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 785932 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>sep_2022 &lt;- read_csv(&quot;2022_09-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 701339 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>oct_2022 &lt;- read_csv(&quot;2022_10-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 558685 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>nov_2022 &lt;- read_csv(&quot;2022_11-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 337735 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>dec_2022 &lt;- read_csv(&quot;2022_12-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 181806 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre><pre class=r><code>jan_2023 &lt;- read_csv(&quot;2023_01-divvy-tripdata.csv&quot;)</code></pre><pre><code>## Rows: 190301 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
## dbl  (4): start_lat, start_lng, end_lat, end_lng
## dttm (2): started_at, ended_at
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre></div><div id=check-for-column-consistency class="section level2"><h2>Check for column consistency</h2><p>View to make sure all have the same columns and combine the 12 dataframes into one dataframe and give it a name.</p><pre class=r><code>colnames(feb_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(mar_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(apr_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(may_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(jun_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(jul_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(aug_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(sep_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(oct_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(nov_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(dec_2022)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>colnames(jan_2023)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>str(jan_2023)</code></pre><pre><code>## spc_tbl_ [190,301 × 13] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ ride_id           : chr [1:190301] &quot;F96D5A74A3E41399&quot; &quot;13CB7EB698CEDB88&quot; &quot;BD88A2E670661CE5&quot; &quot;C90792D034FED968&quot; ...
##  $ rideable_type     : chr [1:190301] &quot;electric_bike&quot; &quot;classic_bike&quot; &quot;electric_bike&quot; &quot;classic_bike&quot; ...
##  $ started_at        : POSIXct[1:190301], format: &quot;2023-01-21 20:05:42&quot; &quot;2023-01-10 15:37:36&quot; ...
##  $ ended_at          : POSIXct[1:190301], format: &quot;2023-01-21 20:16:33&quot; &quot;2023-01-10 15:46:05&quot; ...
##  $ start_station_name: chr [1:190301] &quot;Lincoln Ave &amp; Fullerton Ave&quot; &quot;Kimbark Ave &amp; 53rd St&quot; &quot;Western Ave &amp; Lunt Ave&quot; &quot;Kimbark Ave &amp; 53rd St&quot; ...
##  $ start_station_id  : chr [1:190301] &quot;TA1309000058&quot; &quot;TA1309000037&quot; &quot;RP-005&quot; &quot;TA1309000037&quot; ...
##  $ end_station_name  : chr [1:190301] &quot;Hampden Ct &amp; Diversey Ave&quot; &quot;Greenwood Ave &amp; 47th St&quot; &quot;Valli Produce - Evanston Plaza&quot; &quot;Greenwood Ave &amp; 47th St&quot; ...
##  $ end_station_id    : chr [1:190301] &quot;202480.0&quot; &quot;TA1308000002&quot; &quot;599&quot; &quot;TA1308000002&quot; ...
##  $ start_lat         : num [1:190301] 41.9 41.8 42 41.8 41.8 ...
##  $ start_lng         : num [1:190301] -87.6 -87.6 -87.7 -87.6 -87.6 ...
##  $ end_lat           : num [1:190301] 41.9 41.8 42 41.8 41.8 ...
##  $ end_lng           : num [1:190301] -87.6 -87.6 -87.7 -87.6 -87.6 ...
##  $ member_casual     : chr [1:190301] &quot;member&quot; &quot;member&quot; &quot;casual&quot; &quot;member&quot; ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   ride_id = col_character(),
##   ..   rideable_type = col_character(),
##   ..   started_at = col_datetime(format = &quot;&quot;),
##   ..   ended_at = col_datetime(format = &quot;&quot;),
##   ..   start_station_name = col_character(),
##   ..   start_station_id = col_character(),
##   ..   end_station_name = col_character(),
##   ..   end_station_id = col_character(),
##   ..   start_lat = col_double(),
##   ..   start_lng = col_double(),
##   ..   end_lat = col_double(),
##   ..   end_lng = col_double(),
##   ..   member_casual = col_character()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre></div><div id=combine-the-data-frames-into-one-data-frame class="section level2"><h2>Combine the data frames into one data frame</h2><pre class=r><code>feb_2022 &lt;- mutate(feb_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
mar_2022 &lt;- mutate(mar_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
apr_2022 &lt;- mutate(apr_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
may_2022 &lt;- mutate(may_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
jun_2022 &lt;- mutate(jun_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
jul_2022 &lt;- mutate(jul_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
aug_2022 &lt;- mutate(aug_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
sep_2022 &lt;- mutate(sep_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
oct_2022 &lt;- mutate(oct_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
nov_2022 &lt;- mutate(nov_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
dec_2022 &lt;- mutate(dec_2022, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
jan_2023 &lt;- mutate(jan_2023, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
all_trips &lt;- bind_rows(feb_2022, mar_2022, apr_2022, may_2022, jun_2022, jul_2022,
                       aug_2022, sep_2022, oct_2022, nov_2022, dec_2022, jan_2023)</code></pre></div><div id=inspect-the-new-data-frame class="section level2"><h2>Inspect the new data frame</h2><p>Perform an inspection to confirm that the data has remained accurate after the combination, use data observed in the spreadsheet as a reference point for confirmation.</p><pre class=r><code>colnames(all_trips)</code></pre><pre><code>##  [1] &quot;ride_id&quot;            &quot;rideable_type&quot;      &quot;started_at&quot;        
##  [4] &quot;ended_at&quot;           &quot;start_station_name&quot; &quot;start_station_id&quot;  
##  [7] &quot;end_station_name&quot;   &quot;end_station_id&quot;     &quot;start_lat&quot;         
## [10] &quot;start_lng&quot;          &quot;end_lat&quot;            &quot;end_lng&quot;           
## [13] &quot;member_casual&quot;</code></pre><pre class=r><code>str(all_trips)</code></pre><pre><code>## tibble [5,754,248 × 13] (S3: tbl_df/tbl/data.frame)
##  $ ride_id           : chr [1:5754248] &quot;E1E065E7ED285C02&quot; &quot;1602DCDC5B30FFE3&quot; &quot;BE7DD2AF4B55C4AF&quot; &quot;A1789BDF844412BE&quot; ...
##  $ rideable_type     : chr [1:5754248] &quot;classic_bike&quot; &quot;classic_bike&quot; &quot;classic_bike&quot; &quot;classic_bike&quot; ...
##  $ started_at        : POSIXct[1:5754248], format: &quot;2022-02-19 18:08:41&quot; &quot;2022-02-20 17:41:30&quot; ...
##  $ ended_at          : POSIXct[1:5754248], format: &quot;2022-02-19 18:23:56&quot; &quot;2022-02-20 17:45:56&quot; ...
##  $ start_station_name: chr [1:5754248] &quot;State St &amp; Randolph St&quot; &quot;Halsted St &amp; Wrightwood Ave&quot; &quot;State St &amp; Randolph St&quot; &quot;Southport Ave &amp; Waveland Ave&quot; ...
##  $ start_station_id  : chr [1:5754248] &quot;TA1305000029&quot; &quot;TA1309000061&quot; &quot;TA1305000029&quot; &quot;13235&quot; ...
##  $ end_station_name  : chr [1:5754248] &quot;Clark St &amp; Lincoln Ave&quot; &quot;Southport Ave &amp; Wrightwood Ave&quot; &quot;Canal St &amp; Adams St&quot; &quot;Broadway &amp; Sheridan Rd&quot; ...
##  $ end_station_id    : chr [1:5754248] &quot;13179&quot; &quot;TA1307000113&quot; &quot;13011&quot; &quot;13323&quot; ...
##  $ start_lat         : num [1:5754248] 41.9 41.9 41.9 41.9 41.9 ...
##  $ start_lng         : num [1:5754248] -87.6 -87.6 -87.6 -87.7 -87.6 ...
##  $ end_lat           : num [1:5754248] 41.9 41.9 41.9 42 41.9 ...
##  $ end_lng           : num [1:5754248] -87.6 -87.7 -87.6 -87.6 -87.6 ...
##  $ member_casual     : chr [1:5754248] &quot;member&quot; &quot;member&quot; &quot;member&quot; &quot;member&quot; ...</code></pre><pre class=r><code>summary(all_trips)</code></pre><pre><code>##    ride_id          rideable_type        started_at                    
##  Length:5754248     Length:5754248     Min.   :2022-02-01 00:03:18.00  
##  Class :character   Class :character   1st Qu.:2022-06-02 15:18:09.50  
##  Mode  :character   Mode  :character   Median :2022-07-27 22:50:40.50  
##                                        Mean   :2022-07-29 13:28:03.16  
##                                        3rd Qu.:2022-09-22 20:34:47.25  
##                                        Max.   :2023-01-31 23:56:09.00  
##                                                                        
##     ended_at                      start_station_name start_station_id  
##  Min.   :2022-02-01 00:09:37.00   Length:5754248     Length:5754248    
##  1st Qu.:2022-06-02 15:37:50.50   Class :character   Class :character  
##  Median :2022-07-27 23:09:33.00   Mode  :character   Mode  :character  
##  Mean   :2022-07-29 13:47:21.50                                        
##  3rd Qu.:2022-09-22 20:53:25.25                                        
##  Max.   :2023-02-04 04:27:03.00                                        
##                                                                        
##  end_station_name   end_station_id       start_lat       start_lng     
##  Length:5754248     Length:5754248     Min.   :41.64   Min.   :-87.84  
##  Class :character   Class :character   1st Qu.:41.88   1st Qu.:-87.66  
##  Mode  :character   Mode  :character   Median :41.90   Median :-87.64  
##                                        Mean   :41.90   Mean   :-87.65  
##                                        3rd Qu.:41.93   3rd Qu.:-87.63  
##                                        Max.   :42.07   Max.   :-87.52  
##                                                                        
##     end_lat         end_lng       member_casual     
##  Min.   : 0.00   Min.   :-88.14   Length:5754248    
##  1st Qu.:41.88   1st Qu.:-87.66   Class :character  
##  Median :41.90   Median :-87.64   Mode  :character  
##  Mean   :41.90   Mean   :-87.65                     
##  3rd Qu.:41.93   3rd Qu.:-87.63                     
##  Max.   :42.37   Max.   :  0.00                     
##  NA&#39;s   :5899    NA&#39;s   :5899</code></pre></div><div id=data-summary-addressing-missing-data-and-the-linitations-of-the-data class="section level2"><h2>Data summary, addressing missing data and the linitations of the data</h2><ul><li>Some of the data columns have missing values this will be dealt with in the cleaning process.</li><li>A lot of user data is not available due to privacy issues.</li></ul></div></div><div id=processing-the-data-by-cleaning class="section level1"><h1><strong>Processing the data by cleaning</strong></h1><p>This phase involves checking for any data errors, cleaning the data of any errors, transforming said data by adding, then renaming and by removing data as needed, the rounding it up by checking to see that the data is clean and ready for analysis.</p><div id=add-colums class="section level2"><h2>Add colums</h2><p>Adding columns for: date, month, day, ride_length, year, day_of_week, and hour</p><pre class=r><code>all_trips$date &lt;- as.Date(all_trips$started_at)
all_trips$month &lt;- format(as.Date(all_trips$date), &quot;%B&quot;)
all_trips$day &lt;- format(as.Date(all_trips$date), &quot;%d&quot;)
all_trips$year &lt;- format(as.Date(all_trips$date), &quot;%Y&quot;)
all_trips$day_of_week &lt;- format(as.Date(all_trips$date), &quot;%A&quot;)
all_trips$hour &lt;- lubridate::hour(all_trips$started_at)
all_trips$ride_length &lt;- round(as.numeric(difftime(all_trips$ended_at,all_trips$started_at, units = &quot;mins&quot;)),2)</code></pre><p>Add column for seasons</p><pre class=r><code>all_trips &lt;- all_trips %&gt;% mutate(season = recode(month,
                                                  December = &quot;Winter&quot;,
                                                  January = &quot;Winter&quot;,
                                                  February = &quot;Winter&quot;,
                                                  March = &quot;Spring&quot;,
                                                  April = &quot;Spring&quot;,
                                                  May = &quot;Spring&quot;,
                                                  June = &quot;Summer&quot;,
                                                  July = &quot;Summer&quot;,
                                                  August = &quot;Summer&quot;,
                                                  September = &quot;Fall&quot;,
                                                  October = &quot;Fall&quot;,
                                                  November = &quot;Fall&quot;))</code></pre><p>Add a column to represent the time of the day</p><pre class=r><code>all_trips &lt;- all_trips %&gt;% mutate(time_of_day = case_when(
  hour &gt;= 6 &amp; hour &lt; 9 ~ &quot;Early Morning&quot;,
  hour &gt;= 9 &amp; hour &lt; 12 ~ &quot;Mid Morning&quot;,
  hour &gt;= 12 &amp; hour &lt; 18  ~ &quot;Afternoon&quot;,
  hour &gt;= 18 &amp; hour &lt;= 23  ~ &quot;Evening&quot;,
  hour &gt;= 0 &amp; hour &lt; 3  ~ &quot;Early Night&quot;,
  hour &gt;= 3 &amp; hour &lt; 6  ~ &quot;Late Night&quot;))</code></pre></div><div id=find-and-address-missing-values class="section level2"><h2>Find and address missing values</h2><p>Check the user type and rideable type for missing values.</p><pre class=r><code>all_trips %&gt;% filter(is.na(start_station_id)) %&gt;% 
  count(start_station_id, start_station_name, rideable_type, member_casual)</code></pre><pre><code>## # A tibble: 2 × 5
##   start_station_id start_station_name rideable_type member_casual      n
##   &lt;chr&gt;            &lt;chr&gt;              &lt;chr&gt;         &lt;chr&gt;          &lt;int&gt;
## 1 &lt;NA&gt;             &lt;NA&gt;               electric_bike casual        350065
## 2 &lt;NA&gt;             &lt;NA&gt;               electric_bike member        493460</code></pre><p>The missing values have been located in the electric_bike</p><p>Create new column to address missing values and also uniformize the longitude and latitude.</p><pre class=r><code>all_trips &lt;- all_trips %&gt;% 
  mutate(start_lat_round = round(start_lat, digits = 2),
         start_lng_round = round(start_lng, digits = 2),
         end_lat_round = round(end_lat, digits = 2),
         end_lng_round = round(end_lng, digits = 2))</code></pre><p>Fix missing station names and station ID</p><pre class=r><code>all_trips &lt;- all_trips %&gt;% 
  group_by(start_lat_round, start_lng_round) %&gt;% 
  tidyr::fill(start_station_name, .direction = &quot;downup&quot;) %&gt;% 
  ungroup()

all_trips &lt;- all_trips %&gt;% 
  group_by(end_lat_round, end_lng_round) %&gt;% 
  tidyr::fill(end_station_name, .direction = &quot;downup&quot;) %&gt;% 
  ungroup()

all_trips &lt;- all_trips %&gt;% 
  group_by(start_station_name) %&gt;% 
  tidyr::fill(start_station_id, .direction = &quot;downup&quot;) %&gt;% 
  ungroup()

all_trips &lt;- all_trips %&gt;% 
  group_by(end_station_name) %&gt;% 
  tidyr::fill(end_station_id, .direction = &quot;downup&quot;) %&gt;% 
  ungroup()</code></pre><p>Check the data again to make sure the missing values have been fixed</p><pre class=r><code>colSums(is.na(all_trips))</code></pre><pre><code>##            ride_id      rideable_type         started_at           ended_at 
##                  0                  0                  0                  0 
## start_station_name   start_station_id   end_station_name     end_station_id 
##              11929              11929              40880              40880 
##          start_lat          start_lng            end_lat            end_lng 
##                  0                  0               5899               5899 
##      member_casual               date              month                day 
##                  0                  0                  0                  0 
##               year        day_of_week               hour        ride_length 
##                  0                  0                  0                  0 
##             season        time_of_day    start_lat_round    start_lng_round 
##                  0                  0                  0                  0 
##      end_lat_round      end_lng_round 
##               5899               5899</code></pre><p>These shows that some of the missing values can’t be fixed because they lack critical information, this will be handled by removing them from the dataframe. Their number are very small and insignificant so it can be disregarded.</p></div><div id=find-and-clean-testing-or-repair-rides class="section level2"><h2>Find and clean “testing” or “repair” rides</h2><p>Rides that are by the company employees for the purpose of testing or repairs are immaterial to the analysis being done and can actually skew the data. They will be isolated and eliminated.</p><pre class=r><code>all_trips %&gt;% 
  select(start_station_id) %&gt;% 
  count(start_station_id) %&gt;% 
  arrange(desc(n))</code></pre><pre><code>## # A tibble: 1,312 × 2
##    start_station_id     n
##    &lt;chr&gt;            &lt;int&gt;
##  1 13022            81578
##  2 LF-005           46593
##  3 TA1308000050     43541
##  4 13042            42671
##  5 13300            42225
##  6 TA1307000039     38861
##  7 13008            37142
##  8 KA1503000014     36188
##  9 13179            35857
## 10 TA1308000001     35376
## # … with 1,302 more rows</code></pre><pre class=r><code>all_trips %&gt;% 
  select(end_station_id) %&gt;% 
  count(end_station_id) %&gt;% 
  arrange(desc(n))</code></pre><pre><code>## # A tibble: 1,317 × 2
##    end_station_id     n
##    &lt;chr&gt;          &lt;int&gt;
##  1 13022          81458
##  2 LF-005         45159
##  3 TA1308000050   44744
##  4 13042          42189
##  5 KA1503000014   42012
##  6 13300          41533
##  7 &lt;NA&gt;           40880
##  8 TA1307000039   38672
##  9 13008          37270
## 10 13179          36686
## # … with 1,307 more rows</code></pre><p>Filter out the station related to testing and repair</p><pre class=r><code>all_trips %&gt;% filter(start_station_id %in% c(&quot;DIVVY 001&quot;, &quot;DIVVY 001 - Warehouse test station&quot;, 
                                             &quot;Hubbard Bike-checking (LBS-WH-TEST)&quot;, &quot;Pawel Bialowas - Test- PBSC charging station&quot;, &quot;DIVVY CASSETTE REPAIR MOBILE STATION&quot;, 
                                             &quot;2059 Hastings Warehouse Station&quot;, &quot;Hastings WH 2&quot;, &quot;Throop/Hastings Mobile Station&quot;)) %&gt;%
  count(start_station_id)</code></pre><pre><code>## # A tibble: 6 × 2
##   start_station_id                         n
##   &lt;chr&gt;                                &lt;int&gt;
## 1 2059 Hastings Warehouse Station        585
## 2 DIVVY 001                               77
## 3 DIVVY 001 - Warehouse test station      14
## 4 DIVVY CASSETTE REPAIR MOBILE STATION     7
## 5 Hastings WH 2                           14
## 6 Hubbard Bike-checking (LBS-WH-TEST)   8124</code></pre><pre class=r><code>all_trips %&gt;% filter(end_station_id %in% c(&quot;DIVVY 001&quot;, &quot;DIVVY 001 - Warehouse test station&quot;, &quot;Hubbard Bike-checking (LBS-WH-TEST)&quot;, 
                                           &quot;Pawel Bialowas - Test- PBSC charging station&quot;, &quot;DIVVY CASSETTE REPAIR MOBILE STATION&quot;, 
                                           &quot;2059 Hastings Warehouse Station&quot;, &quot;Hastings WH 2&quot;, &quot;Throop/Hastings Mobile Station&quot;)) %&gt;% 
  count(end_station_id)</code></pre><pre><code>## # A tibble: 4 × 2
##   end_station_id                           n
##   &lt;chr&gt;                                &lt;int&gt;
## 1 2059 Hastings Warehouse Station        791
## 2 DIVVY CASSETTE REPAIR MOBILE STATION     7
## 3 Hastings WH 2                          167
## 4 Hubbard Bike-checking (LBS-WH-TEST)    774</code></pre></div><div id=remove-data-with-unreasonable-ride-length class="section level2"><h2>remove data with unreasonable ride length</h2><ul><li>Rides that have a negative ride length will be treated as invalid, this is because the trip start time can’t be greater than the trip end time</li><li>When the rides last more than a day (24hrs) it can be considered invalid because it is probably not being used, it was probably not docked after use.</li><li>The rides that are less than a minute (60s) are probably a docking mistake.</li></ul><pre class=r><code>all_trips &lt;- all_trips %&gt;% 
  filter(ride_length &gt;= 1 &amp; ride_length &lt;= 1440)</code></pre></div><div id=removed-data-that-were-for-the-repair-and-testing-station class="section level2"><h2>Removed data that were for the repair and testing station</h2><pre class=r><code>all_trips_v2 &lt;- all_trips %&gt;%
  filter(!is.na(end_lat) &amp; !is.na(end_lng))

all_trips_v2 &lt;- all_trips_v2 %&gt;% 
  filter(!start_station_id %in% c(&quot;DIVVY 001&quot;, &quot;DIVVY 001 - Warehouse test station&quot;, &quot;Hubbard Bike-checking (LBS-WH-TEST)&quot;, 
                                  &quot;Pawel Bialowas - Test- PBSC charging station&quot;, &quot;DIVVY CASSETTE REPAIR MOBILE STATION&quot;, 
                                  &quot;2059 Hastings Warehouse Station&quot;, &quot;Hastings WH 2&quot;, &quot;Throop/Hastings Mobile Station&quot;))

all_trips_v2 &lt;- all_trips_v2 %&gt;%
  filter(!end_station_id %in% c(&quot;DIVVY 001&quot;, &quot;DIVVY 001 - Warehouse test station&quot;, &quot;Hubbard Bike-checking (LBS-WH-TEST)&quot;, 
                                &quot;Pawel Bialowas - Test- PBSC charging station&quot;, &quot;DIVVY CASSETTE REPAIR MOBILE STATION&quot;, 
                                &quot;2059 Hastings Warehouse Station&quot;, &quot;Hastings WH 2&quot;, &quot;Throop/Hastings Mobile Station&quot;))</code></pre><p>Removed the testing and repair stations and also renamed the new dataframe created.</p><p>check the removed stations for accuracy</p><pre class=r><code>str(all_trips_v2)</code></pre><pre><code>## tibble [5,612,878 × 26] (S3: tbl_df/tbl/data.frame)
##  $ ride_id           : chr [1:5612878] &quot;E1E065E7ED285C02&quot; &quot;1602DCDC5B30FFE3&quot; &quot;BE7DD2AF4B55C4AF&quot; &quot;A1789BDF844412BE&quot; ...
##  $ rideable_type     : chr [1:5612878] &quot;classic_bike&quot; &quot;classic_bike&quot; &quot;classic_bike&quot; &quot;classic_bike&quot; ...
##  $ started_at        : POSIXct[1:5612878], format: &quot;2022-02-19 18:08:41&quot; &quot;2022-02-20 17:41:30&quot; ...
##  $ ended_at          : POSIXct[1:5612878], format: &quot;2022-02-19 18:23:56&quot; &quot;2022-02-20 17:45:56&quot; ...
##  $ start_station_name: chr [1:5612878] &quot;State St &amp; Randolph St&quot; &quot;Halsted St &amp; Wrightwood Ave&quot; &quot;State St &amp; Randolph St&quot; &quot;Southport Ave &amp; Waveland Ave&quot; ...
##  $ start_station_id  : chr [1:5612878] &quot;TA1305000029&quot; &quot;TA1309000061&quot; &quot;TA1305000029&quot; &quot;13235&quot; ...
##  $ end_station_name  : chr [1:5612878] &quot;Clark St &amp; Lincoln Ave&quot; &quot;Southport Ave &amp; Wrightwood Ave&quot; &quot;Canal St &amp; Adams St&quot; &quot;Broadway &amp; Sheridan Rd&quot; ...
##  $ end_station_id    : chr [1:5612878] &quot;13179&quot; &quot;TA1307000113&quot; &quot;13011&quot; &quot;13323&quot; ...
##  $ start_lat         : num [1:5612878] 41.9 41.9 41.9 41.9 41.9 ...
##  $ start_lng         : num [1:5612878] -87.6 -87.6 -87.6 -87.7 -87.6 ...
##  $ end_lat           : num [1:5612878] 41.9 41.9 41.9 42 41.9 ...
##  $ end_lng           : num [1:5612878] -87.6 -87.7 -87.6 -87.6 -87.6 ...
##  $ member_casual     : chr [1:5612878] &quot;member&quot; &quot;member&quot; &quot;member&quot; &quot;member&quot; ...
##  $ date              : Date[1:5612878], format: &quot;2022-02-19&quot; &quot;2022-02-20&quot; ...
##  $ month             : chr [1:5612878] &quot;February&quot; &quot;February&quot; &quot;February&quot; &quot;February&quot; ...
##  $ day               : chr [1:5612878] &quot;19&quot; &quot;20&quot; &quot;25&quot; &quot;14&quot; ...
##  $ year              : chr [1:5612878] &quot;2022&quot; &quot;2022&quot; &quot;2022&quot; &quot;2022&quot; ...
##  $ day_of_week       : chr [1:5612878] &quot;Saturday&quot; &quot;Sunday&quot; &quot;Friday&quot; &quot;Monday&quot; ...
##  $ hour              : int [1:5612878] 18 17 18 11 5 9 10 20 13 7 ...
##  $ ride_length       : num [1:5612878] 15.25 4.43 13.63 6.95 2.9 ...
##  $ season            : chr [1:5612878] &quot;Winter&quot; &quot;Winter&quot; &quot;Winter&quot; &quot;Winter&quot; ...
##  $ time_of_day       : chr [1:5612878] &quot;Evening&quot; &quot;Afternoon&quot; &quot;Evening&quot; &quot;Mid Morning&quot; ...
##  $ start_lat_round   : num [1:5612878] 41.9 41.9 41.9 42 41.9 ...
##  $ start_lng_round   : num [1:5612878] -87.6 -87.7 -87.6 -87.7 -87.6 ...
##  $ end_lat_round     : num [1:5612878] 41.9 41.9 41.9 42 41.9 ...
##  $ end_lng_round     : num [1:5612878] -87.6 -87.7 -87.6 -87.7 -87.6 ...</code></pre><pre class=r><code>is.factor(all_trips_v2$ride_length)</code></pre><pre><code>## [1] FALSE</code></pre><pre class=r><code>all_trips_v2$ride_length &lt;- as.numeric(as.character(all_trips_v2$ride_length))
is.numeric(all_trips_v2$ride_length)</code></pre><pre><code>## [1] TRUE</code></pre><pre class=r><code>all_trips_v2%&gt;% 
  select(start_station_id) %&gt;% 
  count(start_station_id) %&gt;% 
  arrange(desc(n))</code></pre><pre><code>## # A tibble: 1,306 × 2
##    start_station_id     n
##    &lt;chr&gt;            &lt;int&gt;
##  1 13022            79566
##  2 LF-005           45310
##  3 TA1308000050     42731
##  4 13042            41847
##  5 13300            41325
##  6 TA1307000039     38115
##  7 13008            36247
##  8 KA1503000014     35531
##  9 13179            35118
## 10 TA1308000001     34776
## # … with 1,296 more rows</code></pre><pre class=r><code>all_trips_v2%&gt;% 
  select(end_station_id) %&gt;% 
  count(end_station_id) %&gt;% 
  arrange(desc(n))</code></pre><pre><code>## # A tibble: 1,313 × 2
##    end_station_id     n
##    &lt;chr&gt;          &lt;int&gt;
##  1 13022          79717
##  2 LF-005         44366
##  3 TA1308000050   43686
##  4 13042          41423
##  5 KA1503000014   41239
##  6 13300          40734
##  7 TA1307000039   37702
##  8 13008          36598
##  9 13179          35887
## 10 TA1308000001   34615
## # … with 1,303 more rows</code></pre><pre class=r><code>class(all_trips_v2)</code></pre><pre><code>## [1] &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre><pre class=r><code>colSums(is.na(all_trips_v2))</code></pre><pre><code>##            ride_id      rideable_type         started_at           ended_at 
##                  0                  0                  0                  0 
## start_station_name   start_station_id   end_station_name     end_station_id 
##              11558              11558              33871              33871 
##          start_lat          start_lng            end_lat            end_lng 
##                  0                  0                  0                  0 
##      member_casual               date              month                day 
##                  0                  0                  0                  0 
##               year        day_of_week               hour        ride_length 
##                  0                  0                  0                  0 
##             season        time_of_day    start_lat_round    start_lng_round 
##                  0                  0                  0                  0 
##      end_lat_round      end_lng_round 
##                  0                  0</code></pre><pre class=r><code>skim_without_charts(all_trips_v2)</code></pre><table><caption><span id=tab:unnamed-chunk-17>Table 1: </span>Data summary</caption><tbody><tr class=odd><td align=left>Name</td><td align=left>all_trips_v2</td></tr><tr class=even><td align=left>Number of rows</td><td align=left>5612878</td></tr><tr class=odd><td align=left>Number of columns</td><td align=left>26</td></tr><tr class=even><td align=left>_______________________</td><td align=left></td></tr><tr class=odd><td align=left>Column type frequency:</td><td align=left></td></tr><tr class=even><td align=left>character</td><td align=left>13</td></tr><tr class=odd><td align=left>Date</td><td align=left>1</td></tr><tr class=even><td align=left>numeric</td><td align=left>10</td></tr><tr class=odd><td align=left>POSIXct</td><td align=left>2</td></tr><tr class=even><td align=left>________________________</td><td align=left></td></tr><tr class=odd><td align=left>Group variables</td><td align=left>None</td></tr></tbody></table><p><strong>Variable type: character</strong></p><table style=width:100%><col width=24%><col width=12%><col width=18%><col width=5%><col width=5%><col width=7%><col width=11%><col width=14%><thead><tr class=header><th align=left>skim_variable</th><th align=right>n_missing</th><th align=right>complete_rate</th><th align=right>min</th><th align=right>max</th><th align=right>empty</th><th align=right>n_unique</th><th align=right>whitespace</th></tr></thead><tbody><tr class=odd><td align=left>ride_id</td><td align=right>0</td><td align=right>1.00</td><td align=right>16</td><td align=right>16</td><td align=right>0</td><td align=right>5612878</td><td align=right>0</td></tr><tr class=even><td align=left>rideable_type</td><td align=right>0</td><td align=right>1.00</td><td align=right>11</td><td align=right>13</td><td align=right>0</td><td align=right>3</td><td align=right>0</td></tr><tr class=odd><td align=left>start_station_name</td><td align=right>11558</td><td align=right>1.00</td><td align=right>9</td><td align=right>64</td><td align=right>0</td><td align=right>1671</td><td align=right>0</td></tr><tr class=even><td align=left>start_station_id</td><td align=right>11558</td><td align=right>1.00</td><td align=right>3</td><td align=right>37</td><td align=right>0</td><td align=right>1305</td><td align=right>0</td></tr><tr class=odd><td align=left>end_station_name</td><td align=right>33871</td><td align=right>0.99</td><td align=right>9</td><td align=right>64</td><td align=right>0</td><td align=right>1688</td><td align=right>0</td></tr><tr class=even><td align=left>end_station_id</td><td align=right>33871</td><td align=right>0.99</td><td align=right>3</td><td align=right>37</td><td align=right>0</td><td align=right>1312</td><td align=right>0</td></tr><tr class=odd><td align=left>member_casual</td><td align=right>0</td><td align=right>1.00</td><td align=right>6</td><td align=right>6</td><td align=right>0</td><td align=right>2</td><td align=right>0</td></tr><tr class=even><td align=left>month</td><td align=right>0</td><td align=right>1.00</td><td align=right>3</td><td align=right>9</td><td align=right>0</td><td align=right>12</td><td align=right>0</td></tr><tr class=odd><td align=left>day</td><td align=right>0</td><td align=right>1.00</td><td align=right>2</td><td align=right>2</td><td align=right>0</td><td align=right>31</td><td align=right>0</td></tr><tr class=even><td align=left>year</td><td align=right>0</td><td align=right>1.00</td><td align=right>4</td><td align=right>4</td><td align=right>0</td><td align=right>2</td><td align=right>0</td></tr><tr class=odd><td align=left>day_of_week</td><td align=right>0</td><td align=right>1.00</td><td align=right>6</td><td align=right>9</td><td align=right>0</td><td align=right>7</td><td align=right>0</td></tr><tr class=even><td align=left>season</td><td align=right>0</td><td align=right>1.00</td><td align=right>4</td><td align=right>6</td><td align=right>0</td><td align=right>4</td><td align=right>0</td></tr><tr class=odd><td align=left>time_of_day</td><td align=right>0</td><td align=right>1.00</td><td align=right>7</td><td align=right>13</td><td align=right>0</td><td align=right>6</td><td align=right>0</td></tr></tbody></table><p><strong>Variable type: Date</strong></p><table><col width=17%><col width=12%><col width=17%><col width=13%><col width=13%><col width=13%><col width=11%><thead><tr class=header><th align=left>skim_variable</th><th align=right>n_missing</th><th align=right>complete_rate</th><th align=left>min</th><th align=left>max</th><th align=left>median</th><th align=right>n_unique</th></tr></thead><tbody><tr class=odd><td align=left>date</td><td align=right>0</td><td align=right>1</td><td align=left>2022-02-01</td><td align=left>2023-01-31</td><td align=left>2022-07-27</td><td align=right>365</td></tr></tbody></table><p><strong>Variable type: numeric</strong></p><table style=width:100%><col width=17%><col width=11%><col width=15%><col width=7%><col width=6%><col width=7%><col width=7%><col width=7%><col width=7%><col width=8%><thead><tr class=header><th align=left>skim_variable</th><th align=right>n_missing</th><th align=right>complete_rate</th><th align=right>mean</th><th align=right>sd</th><th align=right>p0</th><th align=right>p25</th><th align=right>p50</th><th align=right>p75</th><th align=right>p100</th></tr></thead><tbody><tr class=odd><td align=left>start_lat</td><td align=right>0</td><td align=right>1</td><td align=right>41.90</td><td align=right>0.05</td><td align=right>41.64</td><td align=right>41.88</td><td align=right>41.90</td><td align=right>41.93</td><td align=right>42.07</td></tr><tr class=even><td align=left>start_lng</td><td align=right>0</td><td align=right>1</td><td align=right>-87.65</td><td align=right>0.03</td><td align=right>-87.84</td><td align=right>-87.66</td><td align=right>-87.64</td><td align=right>-87.63</td><td align=right>-87.52</td></tr><tr class=odd><td align=left>end_lat</td><td align=right>0</td><td align=right>1</td><td align=right>41.90</td><td align=right>0.07</td><td align=right>0.00</td><td align=right>41.88</td><td align=right>41.90</td><td align=right>41.93</td><td align=right>42.37</td></tr><tr class=even><td align=left>end_lng</td><td align=right>0</td><td align=right>1</td><td align=right>-87.65</td><td align=right>0.10</td><td align=right>-88.14</td><td align=right>-87.66</td><td align=right>-87.64</td><td align=right>-87.63</td><td align=right>0.00</td></tr><tr class=odd><td align=left>hour</td><td align=right>0</td><td align=right>1</td><td align=right>14.21</td><td align=right>5.03</td><td align=right>0.00</td><td align=right>11.00</td><td align=right>15.00</td><td align=right>18.00</td><td align=right>23.00</td></tr><tr class=even><td align=left>ride_length</td><td align=right>0</td><td align=right>1</td><td align=right>16.46</td><td align=right>28.68</td><td align=right>1.00</td><td align=right>6.02</td><td align=right>10.43</td><td align=right>18.58</td><td align=right>1439.37</td></tr><tr class=odd><td align=left>start_lat_round</td><td align=right>0</td><td align=right>1</td><td align=right>41.90</td><td align=right>0.05</td><td align=right>41.64</td><td align=right>41.88</td><td align=right>41.90</td><td align=right>41.93</td><td align=right>42.07</td></tr><tr class=even><td align=left>start_lng_round</td><td align=right>0</td><td align=right>1</td><td align=right>-87.65</td><td align=right>0.03</td><td align=right>-87.84</td><td align=right>-87.66</td><td align=right>-87.64</td><td align=right>-87.63</td><td align=right>-87.52</td></tr><tr class=odd><td align=left>end_lat_round</td><td align=right>0</td><td align=right>1</td><td align=right>41.90</td><td align=right>0.07</td><td align=right>0.00</td><td align=right>41.88</td><td align=right>41.90</td><td align=right>41.93</td><td align=right>42.37</td></tr><tr class=even><td align=left>end_lng_round</td><td align=right>0</td><td align=right>1</td><td align=right>-87.65</td><td align=right>0.10</td><td align=right>-88.14</td><td align=right>-87.66</td><td align=right>-87.64</td><td align=right>-87.63</td><td align=right>0.00</td></tr></tbody></table><p><strong>Variable type: POSIXct</strong></p><table><col width=13%><col width=9%><col width=13%><col width=18%><col width=18%><col width=18%><col width=8%><thead><tr class=header><th align=left>skim_variable</th><th align=right>n_missing</th><th align=right>complete_rate</th><th align=left>min</th><th align=left>max</th><th align=left>median</th><th align=right>n_unique</th></tr></thead><tbody><tr class=odd><td align=left>started_at</td><td align=right>0</td><td align=right>1</td><td align=left>2022-02-01 00:03:18</td><td align=left>2023-01-31 23:56:09</td><td align=left>2022-07-27 19:51:47</td><td align=right>4724012</td></tr><tr class=even><td align=left>ended_at</td><td align=right>0</td><td align=right>1</td><td align=left>2022-02-01 00:09:37</td><td align=left>2023-02-01 00:28:12</td><td align=left>2022-07-27 20:10:25</td><td align=right>4736481</td></tr></tbody></table></div></div><div id=analysis-and-visualization-of-the-data class="section level1"><h1><strong>Analysis and Visualization of the Data</strong></h1><p>Analyzing the data in order to get different insights from it in different ways. Focusing on analyzing how the annual member riders and the casual riders use Cyclistic bikes differently.</p><div id=summary class="section level2"><h2>Summary</h2><p>Get the summary of the data to be used for analysis in order to get a snapshot of the information.</p><pre class=r><code>summary(all_trips_v2)</code></pre><pre><code>##    ride_id          rideable_type        started_at                    
##  Length:5612878     Length:5612878     Min.   :2022-02-01 00:03:18.00  
##  Class :character   Class :character   1st Qu.:2022-06-02 12:16:51.50  
##  Mode  :character   Mode  :character   Median :2022-07-27 19:51:47.50  
##                                        Mean   :2022-07-29 10:10:19.89  
##                                        3rd Qu.:2022-09-22 19:13:23.50  
##                                        Max.   :2023-01-31 23:56:09.00  
##     ended_at                      start_station_name start_station_id  
##  Min.   :2022-02-01 00:09:37.00   Length:5612878     Length:5612878    
##  1st Qu.:2022-06-02 12:36:19.00   Class :character   Class :character  
##  Median :2022-07-27 20:10:25.00   Mode  :character   Mode  :character  
##  Mean   :2022-07-29 10:26:47.51                                        
##  3rd Qu.:2022-09-22 19:28:37.00                                        
##  Max.   :2023-02-01 00:28:12.00                                        
##  end_station_name   end_station_id       start_lat       start_lng     
##  Length:5612878     Length:5612878     Min.   :41.64   Min.   :-87.84  
##  Class :character   Class :character   1st Qu.:41.88   1st Qu.:-87.66  
##  Mode  :character   Mode  :character   Median :41.90   Median :-87.64  
##                                        Mean   :41.90   Mean   :-87.65  
##                                        3rd Qu.:41.93   3rd Qu.:-87.63  
##                                        Max.   :42.07   Max.   :-87.52  
##     end_lat         end_lng       member_casual           date           
##  Min.   : 0.00   Min.   :-88.14   Length:5612878     Min.   :2022-02-01  
##  1st Qu.:41.88   1st Qu.:-87.66   Class :character   1st Qu.:2022-06-02  
##  Median :41.90   Median :-87.64   Mode  :character   Median :2022-07-27  
##  Mean   :41.90   Mean   :-87.65                      Mean   :2022-07-28  
##  3rd Qu.:41.93   3rd Qu.:-87.63                      3rd Qu.:2022-09-22  
##  Max.   :42.37   Max.   :  0.00                      Max.   :2023-01-31  
##     month               day                year           day_of_week       
##  Length:5612878     Length:5612878     Length:5612878     Length:5612878    
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##       hour        ride_length         season          time_of_day       
##  Min.   : 0.00   Min.   :   1.00   Length:5612878     Length:5612878    
##  1st Qu.:11.00   1st Qu.:   6.02   Class :character   Class :character  
##  Median :15.00   Median :  10.43   Mode  :character   Mode  :character  
##  Mean   :14.21   Mean   :  16.46                                        
##  3rd Qu.:18.00   3rd Qu.:  18.58                                        
##  Max.   :23.00   Max.   :1439.37                                        
##  start_lat_round start_lng_round  end_lat_round   end_lng_round   
##  Min.   :41.64   Min.   :-87.84   Min.   : 0.00   Min.   :-88.14  
##  1st Qu.:41.88   1st Qu.:-87.66   1st Qu.:41.88   1st Qu.:-87.66  
##  Median :41.90   Median :-87.64   Median :41.90   Median :-87.64  
##  Mean   :41.90   Mean   :-87.65   Mean   :41.90   Mean   :-87.65  
##  3rd Qu.:41.93   3rd Qu.:-87.63   3rd Qu.:41.93   3rd Qu.:-87.63  
##  Max.   :42.07   Max.   :-87.52   Max.   :42.37   Max.   :  0.00</code></pre></div><div id=comparism-of-member-riders-to-casual-riders class="section level2"><h2>Comparism of Member riders to Casual Riders</h2><p>Starting off with numbers and percentage comparison</p><pre class=r><code>all_trips_v2%&gt;% 
  group_by(member_casual) %&gt;% 
  summarise(count = n(), Percentage = n()/nrow(all_trips_v2)*100)</code></pre><pre><code>## # A tibble: 2 × 3
##   member_casual   count Percentage
##   &lt;chr&gt;           &lt;int&gt;      &lt;dbl&gt;
## 1 casual        2284633       40.7
## 2 member        3328245       59.3</code></pre><p><strong>Analysis</strong></p><p>During the time frame studied for this analysis (12 month period), 40.7% of the riders that used the rideables were casual riders while about 59.3% of the riders in the same time period were member riders. Converting a portion of the casual riders to members would be very advantageous.</p><p>Visualizing by member type</p><pre class=r><code>ggplot(all_trips_v2, aes(member_casual, fill=member_casual)) +
  geom_bar() +
  labs(x=&quot;User Type&quot;, y=&quot;Count&quot;, title = &quot;Total Rides: Casual vs Member&quot;) +
  annotate(&quot;text&quot;,x=1,y=2000000,label=&quot;2,284,633 / (40.7%)&quot;,color=&quot;black&quot;,size=3.5) +
  annotate(&quot;text&quot;,x=2,y=3000000,label=&quot;3,328,245 / (59.3%)&quot;,color=&quot;black&quot;,size=3.5) </code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-20-1.png width=672></p><p>A majority of the riders (59.3%) are members while the rest (40.7%) are casual riders.</p><p>Visualizing the total rides by the user type and rideable type</p><pre class=r><code>all_trips_v2%&gt;% 
  group_by(member_casual, rideable_type) %&gt;% 
  summarise(count = n()) %&gt;% 
  ggplot(aes(x=member_casual, y=count, fill=rideable_type)) + 
  geom_bar(stat=&quot;identity&quot;, width = 0.3) +
  labs(x=&quot;Rideable Type&quot;, y=&quot;Number of Rides&quot;, title = &quot;Total Rides by user type and rideable type&quot;)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-21-1.png width=672></p><p>The members riders slightly favor the classic bike over the electric bike:
- Most casual riders use electric bikes
- members don’t use docked bikes
- members use both classic and electric bikes almost equally</p></div><div id=analyzing-the-length-of-rides class="section level2"><h2>Analyzing the length of rides</h2><pre class=r><code>summary(all_trips_v2$ride_length)</code></pre><pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00    6.02   10.43   16.46   18.58 1439.37</code></pre><ul><li>The minimum ride length is 1 minute, which is expected due to cleaning</li><li>Average of all ride lengths is 16.46 minutes</li></ul><p>The average length of ride for each trip (in minutes) by the type of user</p><pre class=r><code>aggregate(all_trips_v2$ride_length~all_trips_v2$member_casual, FUN = mean)</code></pre><pre><code>##   all_trips_v2$member_casual all_trips_v2$ride_length
## 1                     casual                 22.10731
## 2                     member                 12.58425</code></pre><p><strong>Analysis</strong>
The casual riders rode the bikes for significantly more time on average than the member riders.</p><p>Breaking down ride lengths for more analysis</p><pre class=r><code>all_trips_v2%&gt;% 
  group_by(member_casual) %&gt;% 
  summarize(&quot;&lt;=5min&quot; = sum(ride_length &lt;=5),
            &quot;&lt;=15min&quot; = sum(ride_length &lt;=15),
            &quot;&lt;=30min&quot; = sum(ride_length &lt;=30),
            &quot;&lt;=45min&quot; = sum(ride_length &lt;=45),
            &quot;&lt;=60min&quot; = sum(ride_length &lt;=60),
            &quot;&gt;2hrs&quot; = sum(ride_length &gt;120),
            &quot;&gt;4hrs&quot; = sum(ride_length &gt;240),
            &quot;&gt;6hrs&quot; = sum(ride_length &gt;360),)</code></pre><pre><code>## # A tibble: 2 × 9
##   member_casual `&lt;=5min` &lt;=15m…¹ &lt;=30m…² &lt;=45m…³ &lt;=60m…⁴ `&gt;2hrs` `&gt;4hrs` `&gt;6hrs`
##   &lt;chr&gt;            &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;
## 1 casual          266189 1278389 1863455 2057141 2142989   33432    5731    3206
## 2 member          757992 2462997 3116478 3273578 3305079    5982    2111    1218
## # … with abbreviated variable names ¹​`&lt;=15min`, ²​`&lt;=30min`, ³​`&lt;=45min`,
## #   ⁴​`&lt;=60min`</code></pre><p><strong>Analysis</strong>
This shows that for both user types, the vast majority of ride length is below 60 minutes, more data would be needed to analyze this trend but I suspect that it’s the maximum endurance of non professional riders. And distances beyond this point most riders will choose another mode of transportation. Perhaps an availability of more electric bikes would encourage longer rides.</p><pre class=r><code>all_trips_v2 %&gt;% 
  group_by(member_casual) %&gt;% 
  summarize(&quot;&lt;10 min&quot; = sum(ride_length &lt;9.99),
            &quot;10-20 min&quot; = sum(ride_length &gt;=10 &amp; ride_length &lt;=19.99),
            &quot;20-30 min&quot; = sum(ride_length &gt;=20 &amp; ride_length &lt;=29.99),
            &quot;30-60 min&quot; = sum(ride_length &gt;=30 &amp; ride_length &lt;=59.99),
            &quot;60-120 min&quot; = sum(ride_length &gt;=60 &amp; ride_length &lt;=119.99),
            &quot;120-240 min&quot; = sum(ride_length &gt;=120 &amp; ride_length &lt;=239.99),
            &quot;240+min&quot; = sum(ride_length &gt;=240))</code></pre><pre><code>## # A tibble: 2 × 8
##   member_casual `&lt;10 min` `10-20 min` 20-30 mi…¹ 30-60…² 60-12…³ 120-2…⁴ 240+m…⁵
##   &lt;chr&gt;             &lt;int&gt;       &lt;int&gt;      &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;
## 1 casual           845416      707829     309833  279832  108280   27712    5731
## 2 member          1844513      954711     316957  188886   17195    3872    2111
## # … with abbreviated variable names ¹​`20-30 min`, ²​`30-60 min`, ³​`60-120 min`,
## #   ⁴​`120-240 min`, ⁵​`240+min`</code></pre><p><strong>Analysis</strong>
This shows that casual riders tend to keep the rideables for much longer than member riders, but the members tend to take shorter rides.</p><pre class=r><code>all_trips_v3 &lt;- all_trips_v2%&gt;% mutate(ride_length_grp = case_when(
  ride_length &lt;9.99 ~ &quot;&lt; 10 min&quot;,
  ride_length &gt;=10 &amp; ride_length &lt;=19.99 ~ &quot;10-20 min&quot;,
  ride_length &gt;=20 &amp; ride_length &lt;=29.99  ~ &quot;20-30 min&quot;,
  ride_length &gt;=30 &amp; ride_length &lt;=59.99  ~ &quot;30-60 min&quot;,
  ride_length &gt;=60 &amp; ride_length &lt;=119.99  ~ &quot;60-120 min&quot;,
  ride_length &gt;=120 &amp; ride_length &lt;=239.99  ~ &quot;120-240 min&quot;,
  ride_length &gt;=240  ~ &quot;240+ min&quot;))</code></pre><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, ride_length_grp) %&gt;% 
  summarise(count = n()) %&gt;% 
  ggplot(aes(x=factor(ride_length_grp, level = c(&quot;&lt; 10 min&quot;, &quot;10-20 min&quot;, &quot;20-30 min&quot;, &quot;30-60 min&quot;,
                                                 &quot;60-120 min&quot;, &quot;120-240 min&quot;, &quot;240+ min&quot;)), y=count, fill=member_casual)) + 
  geom_col(position = &quot;dodge&quot;) +
  labs(x=&quot;Ride Length&quot;, y=&quot;Number of Rides&quot;, title = &quot;Total Rides by user type and ride length grouping&quot;)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-27-1.png width=672></p><p><strong>Analysis</strong>
Most of the rides fall within the 1 to 20 minutes ride length in minutes, this information can be further enhanced by obtaining survey information on riding behaviors.</p><p>Looking at the average ride length of each trip (in minutes) based on user type and the hour of day</p><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, hour) %&gt;% 
  summarise(count = n(), average_ride_length=mean(ride_length)) %&gt;% 
  arrange(member_casual, hour) %&gt;% 
  ggplot(aes(x=factor(hour, level= c(6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4,5)), y=average_ride_length, fill=member_casual)) + 
  geom_col(position = &quot;dodge&quot;) +
  labs(x=&quot;Hour of day&quot;, y=&quot;Ride Length (in minutes)&quot;, title = &quot;Average ride length by user type and hour of the day&quot;)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-28-1.png width=672></p><p><strong>Analysis</strong>
The casual riders had on average longer rides than member riders peaking between 10AM - 3PM, while member riders stayed relatively constant throughout the day.This insight can be useful in planning maintenance times for the rideables.</p><pre class=r><code>axis_labels &lt;- c(&quot;Early Morning \n6am-9am&quot;, &quot;Mid Morning \n9am-12pm&quot;, &quot;Afternoon \n12pm-6pm&quot;, &quot;Evening \n6pm-11pm&quot;, &quot;Early Night \n11pm-3am&quot;, &quot;Wee Night \n3am-6am&quot;)
all_trips_v3 %&gt;% 
  group_by(member_casual, time_of_day) %&gt;% 
  summarise(count = n(), average_ride_length=mean(ride_length)) %&gt;% 
  ggplot(aes(x=factor(time_of_day, level= c(&quot;Early Morning&quot;, &quot;Mid Morning&quot;, &quot;Afternoon&quot;, &quot;Evening&quot;, &quot;Early Night&quot;, &quot;Late Night&quot;)), y=average_ride_length, fill=member_casual)) + 
  geom_col(position = &quot;dodge&quot;, width = 0.4) +
  labs(x=&quot;Time of Day&quot;, y=&quot;Ride Length (minutes)&quot;, title = &quot;Average ride length by user type and time of the day&quot;) +
  scale_x_discrete(labels = axis_labels)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-29-1.png width=672>
<strong>Analysis</strong></p><ul><li>The length of the bike ride for the casual riders peaks during the mid morning through the afternoon</li><li>The length of the bike ride for member riders remains more constant throughout the day</li></ul><pre class=r><code>aggregate(all_trips_v3$ride_length ~ all_trips_v3$member_casual + 
            all_trips_v3$day_of_week, FUN = mean)</code></pre><pre><code>##    all_trips_v3$member_casual all_trips_v3$day_of_week all_trips_v3$ride_length
## 1                      casual                   Friday                 20.71813
## 2                      member                   Friday                 12.39689
## 3                      casual                   Monday                 22.55896
## 4                      member                   Monday                 12.15048
## 5                      casual                 Saturday                 24.84920
## 6                      member                 Saturday                 14.04720
## 7                      casual                   Sunday                 25.31523
## 8                      member                   Sunday                 13.92415
## 9                      casual                 Thursday                 19.70325
## 10                     member                 Thursday                 12.16705
## 11                     casual                  Tuesday                 19.76585
## 12                     member                  Tuesday                 11.94311
## 13                     casual                Wednesday                 19.07947
## 14                     member                Wednesday                 11.99994</code></pre><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, day_of_week) %&gt;% 
  summarise(count = n(), average_ride_length=mean(ride_length)) %&gt;% 
  ggplot(aes(x=factor(day_of_week, level= c(&quot;Monday&quot;, &quot;Tuesday&quot;, &quot;Wednesday&quot;, &quot;Thursday&quot;, &quot;Friday&quot;, &quot;Saturday&quot;, &quot;Sunday&quot;)), y=average_ride_length, fill=member_casual)) + 
  geom_col(position = &quot;dodge&quot;, width = 0.4) + 
  labs(x=&quot;Day of Week&quot;, y=&quot;Ride Length ( minutes)&quot;, title = &quot;Average ride length by the user type and day of the week&quot;)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-31-1.png width=672></p><p><strong>Analysis</strong></p><p>The weekends saw increased bike use by minutes for both user types, casual riders were consistent throughout the week up until Saturday which is their preferred day of week. Meanwhile, the member riders looked to have a consistent weekly ride and a small weekend spike on the weekend for their bike use. The most popular day for minutes used for both user types is on Sundays.</p><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, hour) %&gt;% 
  summarise(count = n()) %&gt;%  
  arrange(member_casual, hour) %&gt;% 
  ggplot(aes(x=factor(hour, level= c(6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4,5)), y=count, fill=member_casual)) + 
  geom_col(position = &quot;dodge&quot;) +
  labs(x=&quot;Hour of the day&quot;, y=&quot;Number of Rides&quot;, title = &quot;Total Rides by user type and hour of the day&quot;)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-32-1.png width=672></p><p><strong>Analysis</strong></p><ul><li>The member riders show an increased use of rideables starting from 6am and peaking at 8am and they see another peak from 4pm to 6pm.</li><li>The Casual riders only peak from 4pm to 6 pm.</li></ul><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual) %&gt;% 
  summarize(&quot;Early Morning&quot; = sum(time_of_day == &quot;Early Morning&quot;),
            &quot;Mid Morning&quot; = sum(time_of_day == &quot;Mid Morning&quot;),
            &quot;Afternoon&quot; = sum(time_of_day == &quot;Afternoon&quot;),
            &quot;Evening&quot; = sum(time_of_day == &quot;Evening&quot;),
            &quot;Early Night&quot; = sum(time_of_day == &quot;Early Night&quot;),
            &quot;Late Night&quot; = sum(time_of_day == &quot;Late Night&quot;))</code></pre><pre><code>## # A tibble: 2 × 7
##   member_casual `Early Morning` `Mid Morning` Afternoon Evening Early …¹ Late …²
##   &lt;chr&gt;                   &lt;int&gt;         &lt;int&gt;     &lt;int&gt;   &lt;int&gt;    &lt;int&gt;   &lt;int&gt;
## 1 casual                 150178        282434   1034339  694212    92950   30520
## 2 member                 470104        440497   1412537  885751    70557   48799
## # … with abbreviated variable names ¹​`Early Night`, ²​`Late Night`</code></pre><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, time_of_day) %&gt;% 
  summarise(count = n()) %&gt;% 
  ggplot(aes(x=factor(time_of_day, level= c(&quot;Early Morning&quot;, &quot;Mid Morning&quot;, &quot;Afternoon&quot;, &quot;Evening&quot;, &quot;Early Night&quot;, &quot;Late Night&quot;)), y=count, fill=member_casual)) + 
  geom_col(position = &quot;dodge&quot;, width = 0.4) + 
  labs(x=&quot;Time of the Day&quot;, y=&quot;Number of Rides&quot;, title = &quot;Total Rides by user type and time of the day&quot;) +
  scale_x_discrete(labels = axis_labels)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-34-1.png width=672></p><p><strong>Analysis</strong></p><ul><li>Member riders out use the causal riders at all times except for during the early night</li><li>Afternoon and evening saw the biggest number of rides for both membership types</li></ul><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, time_of_day) %&gt;% 
  summarise(count = n()) %&gt;% 
  ggplot(aes(x=factor(time_of_day, level= c(&quot;Early Morning&quot;, &quot;Mid Morning&quot;, &quot;Afternoon&quot;, &quot;Evening&quot;, &quot;Early Night&quot;, &quot;Late Night&quot;)), y=count, color=member_casual)) + 
  geom_point() + geom_line(aes(group = member_casual)) +
  labs(x=&quot;Time of the Day&quot;, y=&quot;Number of Rides&quot;, title = &quot;Total Rides by user type and time of the day&quot;) + ylim(0, NA) +
  scale_x_discrete(labels = axis_labels)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-35-1.png width=672></p><p><strong>Analysis</strong></p><p>This follows the trends previously noticed, with peak times, suggestion that maintenance should be done outside of peak hours in order to main rideable availability and create customer satisfaction.</p></div><div id=analysis-of-total-rides-based-on-user-type-and-day-of-the-week class="section level2"><h2>Analysis of total rides based on user type and day of the week</h2><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual) %&gt;% 
  summarize(&quot;Monday&quot; = sum(day_of_week == &quot;Monday&quot;),
            &quot;Tuesday&quot; = sum(day_of_week == &quot;Tuesday&quot;),
            &quot;Wednesday&quot; = sum(day_of_week == &quot;Wednesday&quot;),
            &quot;Thursday&quot; = sum(day_of_week == &quot;Thursday&quot;),
            &quot;Friday&quot; = sum(day_of_week == &quot;Friday&quot;),
            &quot;Saturday&quot; = sum(day_of_week == &quot;Saturday&quot;),
            &quot;Sunday&quot; = sum(day_of_week == &quot;Sunday&quot;))</code></pre><pre><code>## # A tibble: 2 × 8
##   member_casual Monday Tuesday Wednesday Thursday Friday Saturday Sunday
##   &lt;chr&gt;          &lt;int&gt;   &lt;int&gt;     &lt;int&gt;    &lt;int&gt;  &lt;int&gt;    &lt;int&gt;  &lt;int&gt;
## 1 casual        273930  261419    271058   304027 328728   462513 382958
## 2 member        471235  521864    523339   527774 464289   435606 384138</code></pre><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, day_of_week) %&gt;% 
  summarise(count = n()) %&gt;% 
  ggplot(aes(x=factor(day_of_week, level= c(&quot;Monday&quot;, &quot;Tuesday&quot;, &quot;Wednesday&quot;, &quot;Thursday&quot;, &quot;Friday&quot;, &quot;Saturday&quot;, &quot;Sunday&quot;)), y=count, fill=member_casual)) + 
  geom_col(position = &quot;dodge&quot;, width = 0.4) + 
  labs(x=&quot;Day of the Week&quot;, y=&quot;Number of Rides&quot;, title = &quot;Total Rides by user type and day of the week&quot;)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-37-1.png width=672></p><p><strong>Analysis</strong></p><p>The member riders use more rideables during the week while the casual riders use more rideables during the weekends.</p><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, day_of_week) %&gt;% 
  summarise(count = n()) %&gt;% 
  ggplot(aes(x=factor(day_of_week, level= c(&quot;Monday&quot;, &quot;Tuesday&quot;, &quot;Wednesday&quot;, &quot;Thursday&quot;, &quot;Friday&quot;, &quot;Saturday&quot;, &quot;Sunday&quot;)), y=count, color=member_casual)) + 
  geom_point() + geom_line(aes(group = member_casual)) +
  labs(x=&quot;Day of Week&quot;, y=&quot;Number of Rides&quot;, title = &quot;Total Rides by user type and day of the week&quot;) +
  ylim(0, NA)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-38-1.png width=672></p></div><div id=the-analysis-of-the-total-rides-by-the-type-of-user-and-the-season class="section level2"><h2>The analysis of the total rides by the type of user and the season</h2><pre class=r><code>all_trips_v3 %&gt;% 
  group_by(member_casual, season) %&gt;% 
  summarise(count = n()) %&gt;% 
  ggplot(aes(x=factor(season, level= c(&quot;Spring&quot;, &quot;Summer&quot;, &quot;Fall&quot;, &quot;Winter&quot;)), y=count, fill=member_casual)) + 
  geom_col(position = &quot;dodge&quot;, width = 0.4) + 
  labs(x=&quot;Season of the Year&quot;, y=&quot;Number of Rides&quot;, title = &quot;Total Rides by user type and season of the year&quot;)</code></pre><pre><code>## `summarise()` has grouped output by &#39;member_casual&#39;. You can override using the
## `.groups` argument.</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-39-1.png width=672></p><p><strong>Analysis</strong>
Summer saw the highest rideable use and the winter saw the lowest rideable use, this is probably due to the weather. There is little that can be done to mitigate this but heated bikes is an avenue worth exploring.</p><pre class=r><code>all_trips_v3 %&gt;% 
  filter(!(is.na(start_station_name))) %&gt;% 
  filter(member_casual == &quot;casual&quot;) %&gt;% 
  group_by(start_station_name) %&gt;% 
  summarize(count=n()) %&gt;% 
  arrange(-count) %&gt;% 
  top_n(10)</code></pre><pre><code>## Selecting by count</code></pre><pre><code>## # A tibble: 10 × 2
##    start_station_name                 count
##    &lt;chr&gt;                              &lt;int&gt;
##  1 Streeter Dr &amp; Grand Ave            61066
##  2 DuSable Lake Shore Dr &amp; Monroe St  31809
##  3 Michigan Ave &amp; Oak St              26456
##  4 DuSable Lake Shore Dr &amp; North Blvd 26386
##  5 Millennium Park                    26308
##  6 Shedd Aquarium                     20493
##  7 Theater on the Lake                19651
##  8 Wells St &amp; Concord Ln              18923
##  9 Clark St &amp; Lincoln Ave             18419
## 10 Dusable Harbor                     16228</code></pre><pre class=r><code>all_trips_v3 %&gt;% 
  filter(!(is.na(start_station_name))) %&gt;% 
  filter(member_casual == &quot;casual&quot;) %&gt;% 
  group_by(start_station_name) %&gt;% 
  summarize(count=n()) %&gt;% 
  arrange(-count) %&gt;% 
  top_n(10) %&gt;% 
  mutate(start_station_name= fct_reorder(start_station_name, count)) %&gt;% 
  ggplot(aes(x=start_station_name, y=count, fill=count)) +
  geom_bar(stat = &quot;identity&quot;) +
  coord_flip() +
  labs(x=&quot;Number of Rides&quot;, y=&quot;Name of Start Station &quot;, title=&quot;Top 10 starting stations for casual riders&quot;)</code></pre><pre><code>## Selecting by count</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-41-1.png width=672></p><pre class=r><code>all_trips_v3 %&gt;% 
  filter(!(is.na(end_station_name))) %&gt;% 
  filter(member_casual == &quot;casual&quot;) %&gt;% 
  group_by(end_station_name) %&gt;% 
  summarize(count=n()) %&gt;% 
  arrange(-count) %&gt;% 
  top_n(10)</code></pre><pre><code>## Selecting by count</code></pre><pre><code>## # A tibble: 10 × 2
##    end_station_name                   count
##    &lt;chr&gt;                              &lt;int&gt;
##  1 Streeter Dr &amp; Grand Ave            63523
##  2 DuSable Lake Shore Dr &amp; Monroe St  30126
##  3 Millennium Park                    27700
##  4 DuSable Lake Shore Dr &amp; North Blvd 27217
##  5 Michigan Ave &amp; Oak St              27198
##  6 Theater on the Lake                20663
##  7 Clark St &amp; Lincoln Ave             19096
##  8 Wells St &amp; Concord Ln              18814
##  9 Shedd Aquarium                     18584
## 10 Dusable Harbor                     15474</code></pre><pre class=r><code>all_trips_v3 %&gt;% 
  filter(!(is.na(start_station_name))) %&gt;% 
  filter(member_casual == &quot;member&quot;) %&gt;% 
  group_by(start_station_name) %&gt;% 
  summarize(count=n()) %&gt;% 
  arrange(-count) %&gt;% 
  top_n(10)</code></pre><pre><code>## Selecting by count</code></pre><pre><code>## # A tibble: 10 × 2
##    start_station_name           count
##    &lt;chr&gt;                        &lt;int&gt;
##  1 Ellis Ave &amp; 60th St          29268
##  2 Kingsbury St &amp; Kinzie St     25303
##  3 University Ave &amp; 57th St     25261
##  4 Ellis Ave &amp; 55th St          24845
##  5 Clark St &amp; Elm St            23954
##  6 Wells St &amp; Concord Ln        23808
##  7 Clinton St &amp; Washington Blvd 21257
##  8 Wells St &amp; Elm St            20687
##  9 Loomis St &amp; Lexington St     19920
## 10 Broadway &amp; Barry Ave         19672</code></pre><pre class=r><code>all_trips_v3 %&gt;% 
  filter(!(is.na(start_station_name))) %&gt;% 
  filter(member_casual == &quot;member&quot;) %&gt;% 
  group_by(start_station_name) %&gt;% 
  summarize(count=n()) %&gt;% 
  arrange(-count) %&gt;% 
  top_n(10) %&gt;% 
  mutate(start_station_name= fct_reorder(start_station_name, count)) %&gt;% 
  ggplot(aes(x=start_station_name, y=count, fill=count)) +
  geom_bar(stat = &quot;identity&quot;) +
  coord_flip() +
  labs(x=&quot;Number of Rides&quot;, y=&quot;Name of Start Station &quot;, title=&quot;Top 10 starting stations for member riders&quot;)</code></pre><pre><code>## Selecting by count</code></pre><p><img src=/portfolio/cyclistic-bike_files/figure-html/unnamed-chunk-44-1.png width=672></p><pre class=r><code>all_trips_v3 %&gt;% 
  filter(!(is.na(end_station_name))) %&gt;% 
  filter(member_casual == &quot;member&quot;) %&gt;% 
  group_by(end_station_name) %&gt;% 
  summarize(count=n()) %&gt;% 
  arrange(-count) %&gt;% 
  top_n(10)</code></pre><pre><code>## Selecting by count</code></pre><pre><code>## # A tibble: 10 × 2
##    end_station_name             count
##    &lt;chr&gt;                        &lt;int&gt;
##  1 Ellis Ave &amp; 60th St          34214
##  2 Kingsbury St &amp; Kinzie St     25718
##  3 University Ave &amp; 57th St     25095
##  4 Wells St &amp; Concord Ln        24872
##  5 Clark St &amp; Elm St            24082
##  6 Ellis Ave &amp; 55th St          22564
##  7 Clinton St &amp; Washington Blvd 22176
##  8 Clinton St &amp; Madison St      19623
##  9 Broadway &amp; Barry Ave         19552
## 10 Loomis St &amp; Lexington St     19219</code></pre><p><strong>Analysis</strong></p><p>The information on the top 10 end and start station for both riders can be used to determine availability of rideables.</p></div><div id=export-file-for-more-analysis class="section level2"><h2>Export file for more analysis</h2><pre class=r><code>write_csv(all_trips_v3, file = &quot;all_trips_v3.csv&quot;)</code></pre></div></div><div id=conclusion class="section level1"><h1><strong>Conclusion</strong></h1><p>The first phenomenon that is easily noticeable is the stark difference between casual riders and riders with membership subscriptions, there is a significant difference in length of ride between both sets of riders.</p><div id=key-findings class="section level2"><h2>Key Findings</h2><ul><li><p>Apart from the weekends (Saturday and Sunday) the ride length of the member riders remained relatively unchanged.</p></li><li><p>There is a slight uptick (about 16%) in member riders’ length of rides on weekends, it starts on Friday and experiences a sharp drop on Monday. It remains relatively the same until Friday again.</p></li><li><p>The ride length for casual riders changed significantly from day to day with the peek coming on weekends (Saturday and Sunday).</p></li><li><p>There is a visible inverse bell curve for the ride length of the casual riders, from the beginning of the week (Sunday) to the end of the week (Saturday). There is a dip in midweek and then a steady climb until the weekend, then a slow drop after the weekend.</p></li><li><p>Comparing the casual riders to the member riders, there is a doubling (100% increase) in ride length from the member riders to the casual riders. This means that for any giving day of the week the casual riders have twice the ride time of the member riders.</p></li></ul></div><div id=business-task-questions class="section level2"><h2>Business Task Questions</h2><ul><li>How do annual members and casual riders use Cyclistic bikes differently?</li><li>Why would casual riders buy Cyclistic annual memberships?</li><li>How can Cyclistic use digital media to influence casual riders to become members?</li></ul><p><strong>Challenges</strong></p><p>The lack of individual rider identifiers which would have been integral in deciphering the ride patterns of casual riders would have been quite useful. Finding out if the casual riders were repeat users or just one-time users would have been beneficial.</p></div><div id=convincing-casual-riders-to-buy-annual-memberships class="section level2"><h2>Convincing casual riders to buy annual memberships</h2><p>Given the information analyzed, the following steps can be deployed to increase annual membership among casual riders:</p><ul><li>If the cost to rent for a day or 2 is lower than the weekly cost of membership then the cost of a one-day usage should be increased, this would encourage weekend users to subscribe.</li><li>Offer different types of memberships to cater to different types of riders, for example a weekend pass can be offered to capitalize on the weekend spike. The weekday pass can be made cheaper than the weekend pass to encourage weekday casual users.</li><li>Offer members only exclusives with the rides, an example will be bikes reserved for members only, priority bike usage over the weekend due to increased demands</li><li>Run an ad campaign to showcase the benefits of a membership, explain the pricing and the benefits</li><li>Offer a discount if the whole annual membership fee was paid all at once instead of monthly, also offer auto-pay capabilities and make payment as seamless as possible by offering different pay types.</li><li>Explore charging casual riders by the hour, while members are given unlimited ride time</li></ul><p>Overall, more insight could be provided if more data is available, especially individual ride identities. I’m positive that these recommendations provided would convince casual riders to subscribe to a membership, which in turn will lead to increased revenue.</p></div></div></div><footer class=post-footer><ul class=post-tags></ul><div class=share-buttons><a target=_blank rel="noopener noreferrer" aria-label="share Cyclistic Bike-Share Case Study on twitter" href="https://twitter.com/intent/tweet/?text=Cyclistic%20Bike-Share%20Case%20Study&amp;url=%2fportfolio%2fcyclistic-bike%2f&amp;hashtags="><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM195.519 424.544c135.939.0 210.268-112.643 210.268-210.268.0-3.218.0-6.437-.153-9.502 14.406-10.421 26.973-23.448 36.935-38.314-13.18 5.824-27.433 9.809-42.452 11.648 15.326-9.196 26.973-23.602 32.49-40.92-14.252 8.429-30.038 14.56-46.896 17.931-13.487-14.406-32.644-23.295-53.946-23.295-40.767.0-73.87 33.104-73.87 73.87.0 5.824.613 11.494 1.992 16.858-61.456-3.065-115.862-32.49-152.337-77.241-6.284 10.881-9.962 23.601-9.962 37.088.0 25.594 13.027 48.276 32.95 61.456-12.107-.307-23.448-3.678-33.41-9.196v.92c0 35.862 25.441 65.594 59.311 72.49-6.13 1.686-12.72 2.606-19.464 2.606-4.751.0-9.348-.46-13.946-1.38 9.349 29.426 36.628 50.728 68.965 51.341-25.287 19.771-57.164 31.571-91.8 31.571-5.977.0-11.801-.306-17.625-1.073 32.337 21.15 71.264 33.41 112.95 33.41z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share Cyclistic Bike-Share Case Study on linkedin" href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fportfolio%2fcyclistic-bike%2f&amp;title=Cyclistic%20Bike-Share%20Case%20Study&amp;summary=Cyclistic%20Bike-Share%20Case%20Study&amp;source=%2fportfolio%2fcyclistic-bike%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM160.461 423.278V197.561h-75.04v225.717h75.04zm270.539.0V293.839c0-69.333-37.018-101.586-86.381-101.586-39.804.0-57.634 21.891-67.617 37.266v-31.958h-75.021c.995 21.181.0 225.717.0 225.717h75.02V297.222c0-6.748.486-13.492 2.474-18.315 5.414-13.475 17.767-27.434 38.494-27.434 27.135.0 38.007 20.707 38.007 51.037v120.768H431zM123.448 88.722C97.774 88.722 81 105.601 81 127.724c0 21.658 16.264 39.002 41.455 39.002h.484c26.165.0 42.452-17.344 42.452-39.002-.485-22.092-16.241-38.954-41.943-39.002z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share Cyclistic Bike-Share Case Study on reddit" href="https://reddit.com/submit?url=%2fportfolio%2fcyclistic-bike%2f&title=Cyclistic%20Bike-Share%20Case%20Study"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM446 265.638c0-22.964-18.616-41.58-41.58-41.58-11.211.0-21.361 4.457-28.841 11.666-28.424-20.508-67.586-33.757-111.204-35.278l18.941-89.121 61.884 13.157c.756 15.734 13.642 28.29 29.56 28.29 16.407.0 29.706-13.299 29.706-29.701.0-16.403-13.299-29.702-29.706-29.702-11.666.0-21.657 6.792-26.515 16.578l-69.105-14.69c-1.922-.418-3.939-.042-5.585 1.036-1.658 1.073-2.811 2.761-3.224 4.686l-21.152 99.438c-44.258 1.228-84.046 14.494-112.837 35.232-7.468-7.164-17.589-11.591-28.757-11.591-22.965.0-41.585 18.616-41.585 41.58.0 16.896 10.095 31.41 24.568 37.918-.639 4.135-.99 8.328-.99 12.576.0 63.977 74.469 115.836 166.33 115.836s166.334-51.859 166.334-115.836c0-4.218-.347-8.387-.977-12.493 14.564-6.47 24.735-21.034 24.735-38.001zM326.526 373.831c-20.27 20.241-59.115 21.816-70.534 21.816-11.428.0-50.277-1.575-70.522-21.82-3.007-3.008-3.007-7.882.0-10.889 3.003-2.999 7.882-3.003 10.885.0 12.777 12.781 40.11 17.317 59.637 17.317 19.522.0 46.86-4.536 59.657-17.321 3.016-2.999 7.886-2.995 10.885.008 3.008 3.011 3.003 7.882-.008 10.889zm-5.23-48.781c-16.373.0-29.701-13.324-29.701-29.698.0-16.381 13.328-29.714 29.701-29.714 16.378.0 29.706 13.333 29.706 29.714.0 16.374-13.328 29.698-29.706 29.698zM160.91 295.348c0-16.381 13.328-29.71 29.714-29.71 16.369.0 29.689 13.329 29.689 29.71.0 16.373-13.32 29.693-29.689 29.693-16.386.0-29.714-13.32-29.714-29.693z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share Cyclistic Bike-Share Case Study on facebook" href="https://facebook.com/sharer/sharer.php?u=%2fportfolio%2fcyclistic-bike%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H342.978V319.085h66.6l12.672-82.621h-79.272v-53.617c0-22.603 11.073-44.636 46.58-44.636H425.6v-70.34s-32.71-5.582-63.982-5.582c-65.288.0-107.96 39.569-107.96 111.204v62.971h-72.573v82.621h72.573V512h-191.104c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share Cyclistic Bike-Share Case Study on whatsapp" href="https://api.whatsapp.com/send?text=Cyclistic%20Bike-Share%20Case%20Study%20-%20%2fportfolio%2fcyclistic-bike%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zm-58.673 127.703c-33.842-33.881-78.847-52.548-126.798-52.568-98.799.0-179.21 80.405-179.249 179.234-.013 31.593 8.241 62.428 23.927 89.612l-25.429 92.884 95.021-24.925c26.181 14.28 55.659 21.807 85.658 21.816h.074c98.789.0 179.206-80.413 179.247-179.243.018-47.895-18.61-92.93-52.451-126.81zM263.976 403.485h-.06c-26.734-.01-52.954-7.193-75.828-20.767l-5.441-3.229-56.386 14.792 15.05-54.977-3.542-5.637c-14.913-23.72-22.791-51.136-22.779-79.287.033-82.142 66.867-148.971 149.046-148.971 39.793.014 77.199 15.531 105.329 43.692 28.128 28.16 43.609 65.592 43.594 105.4-.034 82.149-66.866 148.983-148.983 148.984zm81.721-111.581c-4.479-2.242-26.499-13.075-30.604-14.571-4.105-1.495-7.091-2.241-10.077 2.241-2.986 4.483-11.569 14.572-14.182 17.562-2.612 2.988-5.225 3.364-9.703 1.12-4.479-2.241-18.91-6.97-36.017-22.23C231.8 264.15 222.81 249.484 220.198 245s-.279-6.908 1.963-9.14c2.016-2.007 4.48-5.232 6.719-7.847 2.24-2.615 2.986-4.484 4.479-7.472 1.493-2.99.747-5.604-.374-7.846-1.119-2.241-10.077-24.288-13.809-33.256-3.635-8.733-7.327-7.55-10.077-7.688-2.609-.13-5.598-.158-8.583-.158-2.986.0-7.839 1.121-11.944 5.604-4.105 4.484-15.675 15.32-15.675 37.364.0 22.046 16.048 43.342 18.287 46.332 2.24 2.99 31.582 48.227 76.511 67.627 10.685 4.615 19.028 7.371 25.533 9.434 10.728 3.41 20.492 2.929 28.209 1.775 8.605-1.285 26.499-10.833 30.231-21.295 3.732-10.464 3.732-19.431 2.612-21.298-1.119-1.869-4.105-2.99-8.583-5.232z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share Cyclistic Bike-Share Case Study on telegram" href="https://telegram.me/share/url?text=Cyclistic%20Bike-Share%20Case%20Study&amp;url=%2fportfolio%2fcyclistic-bike%2f"><svg viewBox="2 2 28 28" height="30" width="30" fill="currentcolor"><path d="M26.49 29.86H5.5a3.37 3.37.0 01-2.47-1 3.35 3.35.0 01-1-2.47V5.48A3.36 3.36.0 013 3 3.37 3.37.0 015.5 2h21A3.38 3.38.0 0129 3a3.36 3.36.0 011 2.46V26.37a3.35 3.35.0 01-1 2.47 3.38 3.38.0 01-2.51 1.02zm-5.38-6.71a.79.79.0 00.85-.66L24.73 9.24a.55.55.0 00-.18-.46.62.62.0 00-.41-.17q-.08.0-16.53 6.11a.59.59.0 00-.41.59.57.57.0 00.43.52l4 1.24 1.61 4.83a.62.62.0 00.63.43.56.56.0 00.4-.17L16.54 20l4.09 3A.9.9.0 0021.11 23.15zM13.8 20.71l-1.21-4q8.72-5.55 8.78-5.55c.15.0.23.0.23.16a.18.18.0 010 .06s-2.51 2.3-7.52 6.8z"/></svg></a></div></footer></article></main><footer class=footer><span>&copy; 2023 <a href>Nnamdi Okoli</a></span>
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg></a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script></body></html>